lappend pragmaStatus0 {pragma "INTERFACE" source "E:/xfOpenCV/hls_2018_1/abmofParseEvents/src/abmof_hw_accel.cpp" location "parseEvents" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus1 {pragma "INTERFACE" source "E:/xfOpenCV/hls_2018_1/abmofParseEvents/src/abmof_hw_accel.cpp" location "parseEvents" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus2 {pragma "INLINE" source "E:/xfOpenCV/hls_2018_1/abmofParseEvents/src/abmof_hw_accel.cpp" location "accumulateHW" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus3 {pragma "PIPELINE" source "E:/xfOpenCV/hls_2018_1/abmofParseEvents/src/abmof_hw_accel.cpp" location "parseEvents/loop_1" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus4 {pragma "DEPENDENCE" source "E:/xfOpenCV/hls_2018_1/abmofParseEvents/src/abmof_hw_accel.cpp" location "parseEvents" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "glPLSlices"}
lappend pragmaStatus5 {pragma "RESOURCE" source "E:/xfOpenCV/hls_2018_1/abmofParseEvents/src/abmof_hw_accel.cpp" location "parseEvents" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "glPLSlices"}
lappend pragmaStatus6 {pragma "ARRAY_PARTITION" source "E:/xfOpenCV/hls_2018_1/abmofParseEvents/src/abmof_hw_accel.cpp" location "parseEvents" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "glPLSlices"}
lappend pragmaStatus7 {pragma "OCCURRENCE" source "E:/xfOpenCV/hls_2018_1/abmofParseEvents/src/abmof_hw_accel.cpp" location "parseEvents/Cond_Region" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus8 {pragma "ARRAY_PARTITION" source "E:/xfOpenCV/hls_2018_1/abmofParseEvents/src/abmof_hw_accel.cpp" location "parseEvents" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "refBlock"}
lappend pragmaStatus9 {pragma "ARRAY_PARTITION" source "E:/xfOpenCV/hls_2018_1/abmofParseEvents/src/abmof_hw_accel.cpp" location "parseEvents" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "targetBlocks"}
lappend pragmaStatus10 {pragma "RESOURCE" source "E:/xfOpenCV/hls_2018_1/abmofParseEvents/src/abmof_hw_accel.cpp" location "calcOF/readRefBlockLoop1" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "tmp1"}
lappend pragmaStatus11 {pragma "RESOURCE" source "E:/xfOpenCV/hls_2018_1/abmofParseEvents/src/abmof_hw_accel.cpp" location "calcOF/readRefBlockLoop1" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "tmp2"}
lappend pragmaStatus12 {pragma "ALLOCATION" source "E:/xfOpenCV/hls_2018_1/abmofParseEvents/src/abmof_hw_accel.cpp" location "calcOF" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus13 {pragma "RESOURCE" source "E:/xfOpenCV/hls_2018_1/abmofParseEvents/src/abmof_hw_accel.cpp" location "calcOF/calOFInnerLoop1" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'AddSub_DSP' cannot be applied: Variable 'tmpSum' has no assigment in 'calcOF/calOFInnerLoop1'." variable "tmpSum"}
lappend pragmaStatus14 {pragma "RESOURCE" source "E:/xfOpenCV/hls_2018_1/abmofParseEvents/src/abmof_hw_accel.cpp" location "calcOF/calOFInnerLoop1" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "tmpSum"}
