// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module accumulateHW (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x,
        y,
        pol,
        glPLActiveSliceIdx_V,
        glPLSlice0_V_0_address0,
        glPLSlice0_V_0_ce0,
        glPLSlice0_V_0_we0,
        glPLSlice0_V_0_d0,
        glPLSlice0_V_0_q0,
        glPLSlice0_V_1_address0,
        glPLSlice0_V_1_ce0,
        glPLSlice0_V_1_we0,
        glPLSlice0_V_1_d0,
        glPLSlice0_V_1_q0,
        glPLSlice0_V_2_address0,
        glPLSlice0_V_2_ce0,
        glPLSlice0_V_2_we0,
        glPLSlice0_V_2_d0,
        glPLSlice0_V_2_q0,
        glPLSlice0_V_3_address0,
        glPLSlice0_V_3_ce0,
        glPLSlice0_V_3_we0,
        glPLSlice0_V_3_d0,
        glPLSlice0_V_3_q0,
        glPLSlice0_V_4_address0,
        glPLSlice0_V_4_ce0,
        glPLSlice0_V_4_we0,
        glPLSlice0_V_4_d0,
        glPLSlice0_V_4_q0,
        glPLSlice0_V_5_address0,
        glPLSlice0_V_5_ce0,
        glPLSlice0_V_5_we0,
        glPLSlice0_V_5_d0,
        glPLSlice0_V_5_q0,
        glPLSlice0_V_6_address0,
        glPLSlice0_V_6_ce0,
        glPLSlice0_V_6_we0,
        glPLSlice0_V_6_d0,
        glPLSlice0_V_6_q0,
        glPLSlice0_V_7_address0,
        glPLSlice0_V_7_ce0,
        glPLSlice0_V_7_we0,
        glPLSlice0_V_7_d0,
        glPLSlice0_V_7_q0,
        glPLSlice0_V_8_address0,
        glPLSlice0_V_8_ce0,
        glPLSlice0_V_8_we0,
        glPLSlice0_V_8_d0,
        glPLSlice0_V_8_q0,
        glPLSlice0_V_9_address0,
        glPLSlice0_V_9_ce0,
        glPLSlice0_V_9_we0,
        glPLSlice0_V_9_d0,
        glPLSlice0_V_9_q0,
        glPLSlice0_V_10_address0,
        glPLSlice0_V_10_ce0,
        glPLSlice0_V_10_we0,
        glPLSlice0_V_10_d0,
        glPLSlice0_V_10_q0,
        glPLSlice0_V_11_address0,
        glPLSlice0_V_11_ce0,
        glPLSlice0_V_11_we0,
        glPLSlice0_V_11_d0,
        glPLSlice0_V_11_q0,
        glPLSlice0_V_12_address0,
        glPLSlice0_V_12_ce0,
        glPLSlice0_V_12_we0,
        glPLSlice0_V_12_d0,
        glPLSlice0_V_12_q0,
        glPLSlice0_V_13_address0,
        glPLSlice0_V_13_ce0,
        glPLSlice0_V_13_we0,
        glPLSlice0_V_13_d0,
        glPLSlice0_V_13_q0,
        glPLSlice0_V_14_address0,
        glPLSlice0_V_14_ce0,
        glPLSlice0_V_14_we0,
        glPLSlice0_V_14_d0,
        glPLSlice0_V_14_q0,
        glPLSlice0_V_15_address0,
        glPLSlice0_V_15_ce0,
        glPLSlice0_V_15_we0,
        glPLSlice0_V_15_d0,
        glPLSlice0_V_15_q0,
        glPLSlice1_V_0_address0,
        glPLSlice1_V_0_ce0,
        glPLSlice1_V_0_we0,
        glPLSlice1_V_0_d0,
        glPLSlice1_V_0_q0,
        glPLSlice1_V_1_address0,
        glPLSlice1_V_1_ce0,
        glPLSlice1_V_1_we0,
        glPLSlice1_V_1_d0,
        glPLSlice1_V_1_q0,
        glPLSlice1_V_2_address0,
        glPLSlice1_V_2_ce0,
        glPLSlice1_V_2_we0,
        glPLSlice1_V_2_d0,
        glPLSlice1_V_2_q0,
        glPLSlice1_V_3_address0,
        glPLSlice1_V_3_ce0,
        glPLSlice1_V_3_we0,
        glPLSlice1_V_3_d0,
        glPLSlice1_V_3_q0,
        glPLSlice1_V_4_address0,
        glPLSlice1_V_4_ce0,
        glPLSlice1_V_4_we0,
        glPLSlice1_V_4_d0,
        glPLSlice1_V_4_q0,
        glPLSlice1_V_5_address0,
        glPLSlice1_V_5_ce0,
        glPLSlice1_V_5_we0,
        glPLSlice1_V_5_d0,
        glPLSlice1_V_5_q0,
        glPLSlice1_V_6_address0,
        glPLSlice1_V_6_ce0,
        glPLSlice1_V_6_we0,
        glPLSlice1_V_6_d0,
        glPLSlice1_V_6_q0,
        glPLSlice1_V_7_address0,
        glPLSlice1_V_7_ce0,
        glPLSlice1_V_7_we0,
        glPLSlice1_V_7_d0,
        glPLSlice1_V_7_q0,
        glPLSlice1_V_8_address0,
        glPLSlice1_V_8_ce0,
        glPLSlice1_V_8_we0,
        glPLSlice1_V_8_d0,
        glPLSlice1_V_8_q0,
        glPLSlice1_V_9_address0,
        glPLSlice1_V_9_ce0,
        glPLSlice1_V_9_we0,
        glPLSlice1_V_9_d0,
        glPLSlice1_V_9_q0,
        glPLSlice1_V_10_address0,
        glPLSlice1_V_10_ce0,
        glPLSlice1_V_10_we0,
        glPLSlice1_V_10_d0,
        glPLSlice1_V_10_q0,
        glPLSlice1_V_11_address0,
        glPLSlice1_V_11_ce0,
        glPLSlice1_V_11_we0,
        glPLSlice1_V_11_d0,
        glPLSlice1_V_11_q0,
        glPLSlice1_V_12_address0,
        glPLSlice1_V_12_ce0,
        glPLSlice1_V_12_we0,
        glPLSlice1_V_12_d0,
        glPLSlice1_V_12_q0,
        glPLSlice1_V_13_address0,
        glPLSlice1_V_13_ce0,
        glPLSlice1_V_13_we0,
        glPLSlice1_V_13_d0,
        glPLSlice1_V_13_q0,
        glPLSlice1_V_14_address0,
        glPLSlice1_V_14_ce0,
        glPLSlice1_V_14_we0,
        glPLSlice1_V_14_d0,
        glPLSlice1_V_14_q0,
        glPLSlice1_V_15_address0,
        glPLSlice1_V_15_ce0,
        glPLSlice1_V_15_we0,
        glPLSlice1_V_15_d0,
        glPLSlice1_V_15_q0,
        glPLSlice2_V_0_address0,
        glPLSlice2_V_0_ce0,
        glPLSlice2_V_0_we0,
        glPLSlice2_V_0_d0,
        glPLSlice2_V_0_q0,
        glPLSlice2_V_1_address0,
        glPLSlice2_V_1_ce0,
        glPLSlice2_V_1_we0,
        glPLSlice2_V_1_d0,
        glPLSlice2_V_1_q0,
        glPLSlice2_V_2_address0,
        glPLSlice2_V_2_ce0,
        glPLSlice2_V_2_we0,
        glPLSlice2_V_2_d0,
        glPLSlice2_V_2_q0,
        glPLSlice2_V_3_address0,
        glPLSlice2_V_3_ce0,
        glPLSlice2_V_3_we0,
        glPLSlice2_V_3_d0,
        glPLSlice2_V_3_q0,
        glPLSlice2_V_4_address0,
        glPLSlice2_V_4_ce0,
        glPLSlice2_V_4_we0,
        glPLSlice2_V_4_d0,
        glPLSlice2_V_4_q0,
        glPLSlice2_V_5_address0,
        glPLSlice2_V_5_ce0,
        glPLSlice2_V_5_we0,
        glPLSlice2_V_5_d0,
        glPLSlice2_V_5_q0,
        glPLSlice2_V_6_address0,
        glPLSlice2_V_6_ce0,
        glPLSlice2_V_6_we0,
        glPLSlice2_V_6_d0,
        glPLSlice2_V_6_q0,
        glPLSlice2_V_7_address0,
        glPLSlice2_V_7_ce0,
        glPLSlice2_V_7_we0,
        glPLSlice2_V_7_d0,
        glPLSlice2_V_7_q0,
        glPLSlice2_V_8_address0,
        glPLSlice2_V_8_ce0,
        glPLSlice2_V_8_we0,
        glPLSlice2_V_8_d0,
        glPLSlice2_V_8_q0,
        glPLSlice2_V_9_address0,
        glPLSlice2_V_9_ce0,
        glPLSlice2_V_9_we0,
        glPLSlice2_V_9_d0,
        glPLSlice2_V_9_q0,
        glPLSlice2_V_10_address0,
        glPLSlice2_V_10_ce0,
        glPLSlice2_V_10_we0,
        glPLSlice2_V_10_d0,
        glPLSlice2_V_10_q0,
        glPLSlice2_V_11_address0,
        glPLSlice2_V_11_ce0,
        glPLSlice2_V_11_we0,
        glPLSlice2_V_11_d0,
        glPLSlice2_V_11_q0,
        glPLSlice2_V_12_address0,
        glPLSlice2_V_12_ce0,
        glPLSlice2_V_12_we0,
        glPLSlice2_V_12_d0,
        glPLSlice2_V_12_q0,
        glPLSlice2_V_13_address0,
        glPLSlice2_V_13_ce0,
        glPLSlice2_V_13_we0,
        glPLSlice2_V_13_d0,
        glPLSlice2_V_13_q0,
        glPLSlice2_V_14_address0,
        glPLSlice2_V_14_ce0,
        glPLSlice2_V_14_we0,
        glPLSlice2_V_14_d0,
        glPLSlice2_V_14_q0,
        glPLSlice2_V_15_address0,
        glPLSlice2_V_15_ce0,
        glPLSlice2_V_15_we0,
        glPLSlice2_V_15_d0,
        glPLSlice2_V_15_q0,
        ap_ce
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [9:0] x;
input  [8:0] y;
input   pol;
input  [1:0] glPLActiveSliceIdx_V;
output  [5:0] glPLSlice0_V_0_address0;
output   glPLSlice0_V_0_ce0;
output   glPLSlice0_V_0_we0;
output  [179:0] glPLSlice0_V_0_d0;
input  [179:0] glPLSlice0_V_0_q0;
output  [5:0] glPLSlice0_V_1_address0;
output   glPLSlice0_V_1_ce0;
output   glPLSlice0_V_1_we0;
output  [179:0] glPLSlice0_V_1_d0;
input  [179:0] glPLSlice0_V_1_q0;
output  [5:0] glPLSlice0_V_2_address0;
output   glPLSlice0_V_2_ce0;
output   glPLSlice0_V_2_we0;
output  [179:0] glPLSlice0_V_2_d0;
input  [179:0] glPLSlice0_V_2_q0;
output  [5:0] glPLSlice0_V_3_address0;
output   glPLSlice0_V_3_ce0;
output   glPLSlice0_V_3_we0;
output  [179:0] glPLSlice0_V_3_d0;
input  [179:0] glPLSlice0_V_3_q0;
output  [5:0] glPLSlice0_V_4_address0;
output   glPLSlice0_V_4_ce0;
output   glPLSlice0_V_4_we0;
output  [179:0] glPLSlice0_V_4_d0;
input  [179:0] glPLSlice0_V_4_q0;
output  [5:0] glPLSlice0_V_5_address0;
output   glPLSlice0_V_5_ce0;
output   glPLSlice0_V_5_we0;
output  [179:0] glPLSlice0_V_5_d0;
input  [179:0] glPLSlice0_V_5_q0;
output  [5:0] glPLSlice0_V_6_address0;
output   glPLSlice0_V_6_ce0;
output   glPLSlice0_V_6_we0;
output  [179:0] glPLSlice0_V_6_d0;
input  [179:0] glPLSlice0_V_6_q0;
output  [5:0] glPLSlice0_V_7_address0;
output   glPLSlice0_V_7_ce0;
output   glPLSlice0_V_7_we0;
output  [179:0] glPLSlice0_V_7_d0;
input  [179:0] glPLSlice0_V_7_q0;
output  [5:0] glPLSlice0_V_8_address0;
output   glPLSlice0_V_8_ce0;
output   glPLSlice0_V_8_we0;
output  [179:0] glPLSlice0_V_8_d0;
input  [179:0] glPLSlice0_V_8_q0;
output  [5:0] glPLSlice0_V_9_address0;
output   glPLSlice0_V_9_ce0;
output   glPLSlice0_V_9_we0;
output  [179:0] glPLSlice0_V_9_d0;
input  [179:0] glPLSlice0_V_9_q0;
output  [5:0] glPLSlice0_V_10_address0;
output   glPLSlice0_V_10_ce0;
output   glPLSlice0_V_10_we0;
output  [179:0] glPLSlice0_V_10_d0;
input  [179:0] glPLSlice0_V_10_q0;
output  [5:0] glPLSlice0_V_11_address0;
output   glPLSlice0_V_11_ce0;
output   glPLSlice0_V_11_we0;
output  [179:0] glPLSlice0_V_11_d0;
input  [179:0] glPLSlice0_V_11_q0;
output  [5:0] glPLSlice0_V_12_address0;
output   glPLSlice0_V_12_ce0;
output   glPLSlice0_V_12_we0;
output  [179:0] glPLSlice0_V_12_d0;
input  [179:0] glPLSlice0_V_12_q0;
output  [5:0] glPLSlice0_V_13_address0;
output   glPLSlice0_V_13_ce0;
output   glPLSlice0_V_13_we0;
output  [179:0] glPLSlice0_V_13_d0;
input  [179:0] glPLSlice0_V_13_q0;
output  [5:0] glPLSlice0_V_14_address0;
output   glPLSlice0_V_14_ce0;
output   glPLSlice0_V_14_we0;
output  [179:0] glPLSlice0_V_14_d0;
input  [179:0] glPLSlice0_V_14_q0;
output  [5:0] glPLSlice0_V_15_address0;
output   glPLSlice0_V_15_ce0;
output   glPLSlice0_V_15_we0;
output  [179:0] glPLSlice0_V_15_d0;
input  [179:0] glPLSlice0_V_15_q0;
output  [5:0] glPLSlice1_V_0_address0;
output   glPLSlice1_V_0_ce0;
output   glPLSlice1_V_0_we0;
output  [179:0] glPLSlice1_V_0_d0;
input  [179:0] glPLSlice1_V_0_q0;
output  [5:0] glPLSlice1_V_1_address0;
output   glPLSlice1_V_1_ce0;
output   glPLSlice1_V_1_we0;
output  [179:0] glPLSlice1_V_1_d0;
input  [179:0] glPLSlice1_V_1_q0;
output  [5:0] glPLSlice1_V_2_address0;
output   glPLSlice1_V_2_ce0;
output   glPLSlice1_V_2_we0;
output  [179:0] glPLSlice1_V_2_d0;
input  [179:0] glPLSlice1_V_2_q0;
output  [5:0] glPLSlice1_V_3_address0;
output   glPLSlice1_V_3_ce0;
output   glPLSlice1_V_3_we0;
output  [179:0] glPLSlice1_V_3_d0;
input  [179:0] glPLSlice1_V_3_q0;
output  [5:0] glPLSlice1_V_4_address0;
output   glPLSlice1_V_4_ce0;
output   glPLSlice1_V_4_we0;
output  [179:0] glPLSlice1_V_4_d0;
input  [179:0] glPLSlice1_V_4_q0;
output  [5:0] glPLSlice1_V_5_address0;
output   glPLSlice1_V_5_ce0;
output   glPLSlice1_V_5_we0;
output  [179:0] glPLSlice1_V_5_d0;
input  [179:0] glPLSlice1_V_5_q0;
output  [5:0] glPLSlice1_V_6_address0;
output   glPLSlice1_V_6_ce0;
output   glPLSlice1_V_6_we0;
output  [179:0] glPLSlice1_V_6_d0;
input  [179:0] glPLSlice1_V_6_q0;
output  [5:0] glPLSlice1_V_7_address0;
output   glPLSlice1_V_7_ce0;
output   glPLSlice1_V_7_we0;
output  [179:0] glPLSlice1_V_7_d0;
input  [179:0] glPLSlice1_V_7_q0;
output  [5:0] glPLSlice1_V_8_address0;
output   glPLSlice1_V_8_ce0;
output   glPLSlice1_V_8_we0;
output  [179:0] glPLSlice1_V_8_d0;
input  [179:0] glPLSlice1_V_8_q0;
output  [5:0] glPLSlice1_V_9_address0;
output   glPLSlice1_V_9_ce0;
output   glPLSlice1_V_9_we0;
output  [179:0] glPLSlice1_V_9_d0;
input  [179:0] glPLSlice1_V_9_q0;
output  [5:0] glPLSlice1_V_10_address0;
output   glPLSlice1_V_10_ce0;
output   glPLSlice1_V_10_we0;
output  [179:0] glPLSlice1_V_10_d0;
input  [179:0] glPLSlice1_V_10_q0;
output  [5:0] glPLSlice1_V_11_address0;
output   glPLSlice1_V_11_ce0;
output   glPLSlice1_V_11_we0;
output  [179:0] glPLSlice1_V_11_d0;
input  [179:0] glPLSlice1_V_11_q0;
output  [5:0] glPLSlice1_V_12_address0;
output   glPLSlice1_V_12_ce0;
output   glPLSlice1_V_12_we0;
output  [179:0] glPLSlice1_V_12_d0;
input  [179:0] glPLSlice1_V_12_q0;
output  [5:0] glPLSlice1_V_13_address0;
output   glPLSlice1_V_13_ce0;
output   glPLSlice1_V_13_we0;
output  [179:0] glPLSlice1_V_13_d0;
input  [179:0] glPLSlice1_V_13_q0;
output  [5:0] glPLSlice1_V_14_address0;
output   glPLSlice1_V_14_ce0;
output   glPLSlice1_V_14_we0;
output  [179:0] glPLSlice1_V_14_d0;
input  [179:0] glPLSlice1_V_14_q0;
output  [5:0] glPLSlice1_V_15_address0;
output   glPLSlice1_V_15_ce0;
output   glPLSlice1_V_15_we0;
output  [179:0] glPLSlice1_V_15_d0;
input  [179:0] glPLSlice1_V_15_q0;
output  [5:0] glPLSlice2_V_0_address0;
output   glPLSlice2_V_0_ce0;
output   glPLSlice2_V_0_we0;
output  [179:0] glPLSlice2_V_0_d0;
input  [179:0] glPLSlice2_V_0_q0;
output  [5:0] glPLSlice2_V_1_address0;
output   glPLSlice2_V_1_ce0;
output   glPLSlice2_V_1_we0;
output  [179:0] glPLSlice2_V_1_d0;
input  [179:0] glPLSlice2_V_1_q0;
output  [5:0] glPLSlice2_V_2_address0;
output   glPLSlice2_V_2_ce0;
output   glPLSlice2_V_2_we0;
output  [179:0] glPLSlice2_V_2_d0;
input  [179:0] glPLSlice2_V_2_q0;
output  [5:0] glPLSlice2_V_3_address0;
output   glPLSlice2_V_3_ce0;
output   glPLSlice2_V_3_we0;
output  [179:0] glPLSlice2_V_3_d0;
input  [179:0] glPLSlice2_V_3_q0;
output  [5:0] glPLSlice2_V_4_address0;
output   glPLSlice2_V_4_ce0;
output   glPLSlice2_V_4_we0;
output  [179:0] glPLSlice2_V_4_d0;
input  [179:0] glPLSlice2_V_4_q0;
output  [5:0] glPLSlice2_V_5_address0;
output   glPLSlice2_V_5_ce0;
output   glPLSlice2_V_5_we0;
output  [179:0] glPLSlice2_V_5_d0;
input  [179:0] glPLSlice2_V_5_q0;
output  [5:0] glPLSlice2_V_6_address0;
output   glPLSlice2_V_6_ce0;
output   glPLSlice2_V_6_we0;
output  [179:0] glPLSlice2_V_6_d0;
input  [179:0] glPLSlice2_V_6_q0;
output  [5:0] glPLSlice2_V_7_address0;
output   glPLSlice2_V_7_ce0;
output   glPLSlice2_V_7_we0;
output  [179:0] glPLSlice2_V_7_d0;
input  [179:0] glPLSlice2_V_7_q0;
output  [5:0] glPLSlice2_V_8_address0;
output   glPLSlice2_V_8_ce0;
output   glPLSlice2_V_8_we0;
output  [179:0] glPLSlice2_V_8_d0;
input  [179:0] glPLSlice2_V_8_q0;
output  [5:0] glPLSlice2_V_9_address0;
output   glPLSlice2_V_9_ce0;
output   glPLSlice2_V_9_we0;
output  [179:0] glPLSlice2_V_9_d0;
input  [179:0] glPLSlice2_V_9_q0;
output  [5:0] glPLSlice2_V_10_address0;
output   glPLSlice2_V_10_ce0;
output   glPLSlice2_V_10_we0;
output  [179:0] glPLSlice2_V_10_d0;
input  [179:0] glPLSlice2_V_10_q0;
output  [5:0] glPLSlice2_V_11_address0;
output   glPLSlice2_V_11_ce0;
output   glPLSlice2_V_11_we0;
output  [179:0] glPLSlice2_V_11_d0;
input  [179:0] glPLSlice2_V_11_q0;
output  [5:0] glPLSlice2_V_12_address0;
output   glPLSlice2_V_12_ce0;
output   glPLSlice2_V_12_we0;
output  [179:0] glPLSlice2_V_12_d0;
input  [179:0] glPLSlice2_V_12_q0;
output  [5:0] glPLSlice2_V_13_address0;
output   glPLSlice2_V_13_ce0;
output   glPLSlice2_V_13_we0;
output  [179:0] glPLSlice2_V_13_d0;
input  [179:0] glPLSlice2_V_13_q0;
output  [5:0] glPLSlice2_V_14_address0;
output   glPLSlice2_V_14_ce0;
output   glPLSlice2_V_14_we0;
output  [179:0] glPLSlice2_V_14_d0;
input  [179:0] glPLSlice2_V_14_q0;
output  [5:0] glPLSlice2_V_15_address0;
output   glPLSlice2_V_15_ce0;
output   glPLSlice2_V_15_we0;
output  [179:0] glPLSlice2_V_15_d0;
input  [179:0] glPLSlice2_V_15_q0;
input   ap_ce;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[5:0] glPLSlice0_V_0_address0;
reg glPLSlice0_V_0_ce0;
reg glPLSlice0_V_0_we0;
reg[5:0] glPLSlice0_V_1_address0;
reg glPLSlice0_V_1_ce0;
reg glPLSlice0_V_1_we0;
reg[5:0] glPLSlice0_V_2_address0;
reg glPLSlice0_V_2_ce0;
reg glPLSlice0_V_2_we0;
reg[5:0] glPLSlice0_V_3_address0;
reg glPLSlice0_V_3_ce0;
reg glPLSlice0_V_3_we0;
reg[5:0] glPLSlice0_V_4_address0;
reg glPLSlice0_V_4_ce0;
reg glPLSlice0_V_4_we0;
reg[5:0] glPLSlice0_V_5_address0;
reg glPLSlice0_V_5_ce0;
reg glPLSlice0_V_5_we0;
reg[5:0] glPLSlice0_V_6_address0;
reg glPLSlice0_V_6_ce0;
reg glPLSlice0_V_6_we0;
reg[5:0] glPLSlice0_V_7_address0;
reg glPLSlice0_V_7_ce0;
reg glPLSlice0_V_7_we0;
reg[5:0] glPLSlice0_V_8_address0;
reg glPLSlice0_V_8_ce0;
reg glPLSlice0_V_8_we0;
reg[5:0] glPLSlice0_V_9_address0;
reg glPLSlice0_V_9_ce0;
reg glPLSlice0_V_9_we0;
reg[5:0] glPLSlice0_V_10_address0;
reg glPLSlice0_V_10_ce0;
reg glPLSlice0_V_10_we0;
reg[5:0] glPLSlice0_V_11_address0;
reg glPLSlice0_V_11_ce0;
reg glPLSlice0_V_11_we0;
reg[5:0] glPLSlice0_V_12_address0;
reg glPLSlice0_V_12_ce0;
reg glPLSlice0_V_12_we0;
reg[5:0] glPLSlice0_V_13_address0;
reg glPLSlice0_V_13_ce0;
reg glPLSlice0_V_13_we0;
reg[5:0] glPLSlice0_V_14_address0;
reg glPLSlice0_V_14_ce0;
reg glPLSlice0_V_14_we0;
reg[5:0] glPLSlice0_V_15_address0;
reg glPLSlice0_V_15_ce0;
reg glPLSlice0_V_15_we0;
reg[5:0] glPLSlice1_V_0_address0;
reg glPLSlice1_V_0_ce0;
reg glPLSlice1_V_0_we0;
reg[5:0] glPLSlice1_V_1_address0;
reg glPLSlice1_V_1_ce0;
reg glPLSlice1_V_1_we0;
reg[5:0] glPLSlice1_V_2_address0;
reg glPLSlice1_V_2_ce0;
reg glPLSlice1_V_2_we0;
reg[5:0] glPLSlice1_V_3_address0;
reg glPLSlice1_V_3_ce0;
reg glPLSlice1_V_3_we0;
reg[5:0] glPLSlice1_V_4_address0;
reg glPLSlice1_V_4_ce0;
reg glPLSlice1_V_4_we0;
reg[5:0] glPLSlice1_V_5_address0;
reg glPLSlice1_V_5_ce0;
reg glPLSlice1_V_5_we0;
reg[5:0] glPLSlice1_V_6_address0;
reg glPLSlice1_V_6_ce0;
reg glPLSlice1_V_6_we0;
reg[5:0] glPLSlice1_V_7_address0;
reg glPLSlice1_V_7_ce0;
reg glPLSlice1_V_7_we0;
reg[5:0] glPLSlice1_V_8_address0;
reg glPLSlice1_V_8_ce0;
reg glPLSlice1_V_8_we0;
reg[5:0] glPLSlice1_V_9_address0;
reg glPLSlice1_V_9_ce0;
reg glPLSlice1_V_9_we0;
reg[5:0] glPLSlice1_V_10_address0;
reg glPLSlice1_V_10_ce0;
reg glPLSlice1_V_10_we0;
reg[5:0] glPLSlice1_V_11_address0;
reg glPLSlice1_V_11_ce0;
reg glPLSlice1_V_11_we0;
reg[5:0] glPLSlice1_V_12_address0;
reg glPLSlice1_V_12_ce0;
reg glPLSlice1_V_12_we0;
reg[5:0] glPLSlice1_V_13_address0;
reg glPLSlice1_V_13_ce0;
reg glPLSlice1_V_13_we0;
reg[5:0] glPLSlice1_V_14_address0;
reg glPLSlice1_V_14_ce0;
reg glPLSlice1_V_14_we0;
reg[5:0] glPLSlice1_V_15_address0;
reg glPLSlice1_V_15_ce0;
reg glPLSlice1_V_15_we0;
reg[5:0] glPLSlice2_V_0_address0;
reg glPLSlice2_V_0_ce0;
reg glPLSlice2_V_0_we0;
reg[5:0] glPLSlice2_V_1_address0;
reg glPLSlice2_V_1_ce0;
reg glPLSlice2_V_1_we0;
reg[5:0] glPLSlice2_V_2_address0;
reg glPLSlice2_V_2_ce0;
reg glPLSlice2_V_2_we0;
reg[5:0] glPLSlice2_V_3_address0;
reg glPLSlice2_V_3_ce0;
reg glPLSlice2_V_3_we0;
reg[5:0] glPLSlice2_V_4_address0;
reg glPLSlice2_V_4_ce0;
reg glPLSlice2_V_4_we0;
reg[5:0] glPLSlice2_V_5_address0;
reg glPLSlice2_V_5_ce0;
reg glPLSlice2_V_5_we0;
reg[5:0] glPLSlice2_V_6_address0;
reg glPLSlice2_V_6_ce0;
reg glPLSlice2_V_6_we0;
reg[5:0] glPLSlice2_V_7_address0;
reg glPLSlice2_V_7_ce0;
reg glPLSlice2_V_7_we0;
reg[5:0] glPLSlice2_V_8_address0;
reg glPLSlice2_V_8_ce0;
reg glPLSlice2_V_8_we0;
reg[5:0] glPLSlice2_V_9_address0;
reg glPLSlice2_V_9_ce0;
reg glPLSlice2_V_9_we0;
reg[5:0] glPLSlice2_V_10_address0;
reg glPLSlice2_V_10_ce0;
reg glPLSlice2_V_10_we0;
reg[5:0] glPLSlice2_V_11_address0;
reg glPLSlice2_V_11_ce0;
reg glPLSlice2_V_11_we0;
reg[5:0] glPLSlice2_V_12_address0;
reg glPLSlice2_V_12_ce0;
reg glPLSlice2_V_12_we0;
reg[5:0] glPLSlice2_V_13_address0;
reg glPLSlice2_V_13_ce0;
reg glPLSlice2_V_13_we0;
reg[5:0] glPLSlice2_V_14_address0;
reg glPLSlice2_V_14_ce0;
reg glPLSlice2_V_14_we0;
reg[5:0] glPLSlice2_V_15_address0;
reg glPLSlice2_V_15_ce0;
reg glPLSlice2_V_15_we0;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] pol_read_read_fu_190_p2;
reg   [0:0] pol_read_reg_1554;
wire  signed [8:0] tmp_12_fu_823_p3;
reg  signed [8:0] tmp_12_reg_1558;
wire   [9:0] xNewIdx_V_fu_841_p2;
reg   [9:0] xNewIdx_V_reg_1567;
wire   [0:0] tmp_13_fu_852_p2;
reg   [0:0] tmp_13_reg_1574;
wire   [0:0] tmp_21_fu_858_p2;
reg   [0:0] tmp_21_reg_1578;
wire   [0:0] tmp_26_fu_864_p2;
reg   [0:0] tmp_26_reg_1582;
reg   [5:0] glPLSlice2_V_0_addr_reg_1586;
reg   [5:0] glPLSlice2_V_1_addr_reg_1591;
reg   [5:0] glPLSlice2_V_2_addr_reg_1596;
reg   [5:0] glPLSlice2_V_3_addr_reg_1601;
reg   [5:0] glPLSlice2_V_4_addr_reg_1606;
reg   [5:0] glPLSlice2_V_5_addr_reg_1611;
reg   [5:0] glPLSlice2_V_6_addr_reg_1616;
reg   [5:0] glPLSlice2_V_7_addr_reg_1621;
reg   [5:0] glPLSlice2_V_8_addr_reg_1626;
reg   [5:0] glPLSlice2_V_9_addr_reg_1631;
reg   [5:0] glPLSlice2_V_10_addr_reg_1636;
reg   [5:0] glPLSlice2_V_11_addr_reg_1641;
reg   [5:0] glPLSlice2_V_12_addr_reg_1646;
reg   [5:0] glPLSlice2_V_13_addr_reg_1651;
reg   [5:0] glPLSlice2_V_14_addr_reg_1656;
reg   [5:0] glPLSlice2_V_15_addr_reg_1661;
reg   [5:0] glPLSlice1_V_0_addr_reg_1666;
reg   [5:0] glPLSlice1_V_1_addr_reg_1671;
reg   [5:0] glPLSlice1_V_2_addr_reg_1676;
reg   [5:0] glPLSlice1_V_3_addr_reg_1681;
reg   [5:0] glPLSlice1_V_4_addr_reg_1686;
reg   [5:0] glPLSlice1_V_5_addr_reg_1691;
reg   [5:0] glPLSlice1_V_6_addr_reg_1696;
reg   [5:0] glPLSlice1_V_7_addr_reg_1701;
reg   [5:0] glPLSlice1_V_8_addr_reg_1706;
reg   [5:0] glPLSlice1_V_9_addr_reg_1711;
reg   [5:0] glPLSlice1_V_10_addr_reg_1716;
reg   [5:0] glPLSlice1_V_11_addr_reg_1721;
reg   [5:0] glPLSlice1_V_12_addr_reg_1726;
reg   [5:0] glPLSlice1_V_13_addr_reg_1731;
reg   [5:0] glPLSlice1_V_14_addr_reg_1736;
reg   [5:0] glPLSlice1_V_15_addr_reg_1741;
reg   [5:0] glPLSlice0_V_0_addr_reg_1746;
reg   [5:0] glPLSlice0_V_1_addr_reg_1751;
reg   [5:0] glPLSlice0_V_2_addr_reg_1756;
reg   [5:0] glPLSlice0_V_3_addr_reg_1761;
reg   [5:0] glPLSlice0_V_4_addr_reg_1766;
reg   [5:0] glPLSlice0_V_5_addr_reg_1771;
reg   [5:0] glPLSlice0_V_6_addr_reg_1776;
reg   [5:0] glPLSlice0_V_7_addr_reg_1781;
reg   [5:0] glPLSlice0_V_8_addr_reg_1786;
reg   [5:0] glPLSlice0_V_9_addr_reg_1791;
reg   [5:0] glPLSlice0_V_10_addr_reg_1796;
reg   [5:0] glPLSlice0_V_11_addr_reg_1801;
reg   [5:0] glPLSlice0_V_12_addr_reg_1806;
reg   [5:0] glPLSlice0_V_13_addr_reg_1811;
reg   [5:0] glPLSlice0_V_14_addr_reg_1816;
reg   [5:0] glPLSlice0_V_15_addr_reg_1821;
wire   [63:0] newIndex6_fu_870_p1;
wire   [63:0] newIndex5_fu_890_p1;
wire   [63:0] newIndex3_fu_910_p1;
wire    ap_CS_fsm_state2;
wire   [3:0] tmp_42_fu_930_p1;
reg   [179:0] tmp_54_fu_1112_p4;
wire   [3:0] tmp_29_fu_1138_p1;
reg   [179:0] tmp_41_fu_1320_p4;
wire   [3:0] tmp_14_fu_1346_p1;
reg   [179:0] tmp_28_fu_1528_p4;
wire   [6:0] tmp_s_fu_813_p4;
wire   [9:0] tmp_fu_807_p2;
wire   [9:0] y_cast_fu_803_p1;
wire   [9:0] p_s_fu_835_p2;
wire  signed [9:0] tmp_30_cast_fu_831_p1;
wire   [5:0] grp_fu_784_p4;
wire   [3:0] tmpData_V_2_fu_933_p17;
wire   [179:0] tmpData_V_2_fu_933_p18;
wire  signed [31:0] tmp_47_cast_fu_971_p1;
wire   [31:0] index_assign_9_s_fu_982_p2;
wire   [8:0] grp_fu_793_p2;
wire  signed [31:0] index_assign_9_1_cas_fu_996_p1;
wire   [8:0] grp_fu_798_p2;
wire  signed [31:0] index_assign_9_2_cas_fu_1008_p1;
wire   [0:0] tmp_46_fu_1012_p3;
wire   [0:0] tmp_45_fu_1000_p3;
wire   [0:0] tmp_44_fu_988_p3;
wire   [0:0] tmp_43_fu_974_p3;
wire   [3:0] p_Result_16_3_fu_1020_p5;
wire   [3:0] tmpTmpData_V_2_fu_1032_p2;
wire   [0:0] tmp_47_fu_1038_p1;
wire   [63:0] p_Repl2_5_fu_1042_p1;
wire   [0:0] tmp_49_fu_1056_p3;
reg   [179:0] tmp_48_fu_1046_p4;
wire   [63:0] p_Repl2_5_1_fu_1064_p1;
wire   [0:0] tmp_51_fu_1078_p3;
reg   [179:0] tmp_50_fu_1068_p4;
wire   [63:0] p_Repl2_5_2_fu_1086_p1;
wire   [0:0] tmp_53_fu_1100_p3;
reg   [179:0] tmp_52_fu_1090_p4;
wire   [63:0] p_Repl2_5_3_fu_1108_p1;
wire   [3:0] tmpData_V_1_fu_1141_p17;
wire   [179:0] tmpData_V_1_fu_1141_p18;
wire  signed [31:0] tmp_40_cast_fu_1179_p1;
wire   [31:0] index_assign_5_s_fu_1190_p2;
wire  signed [31:0] index_assign_5_1_cas_fu_1204_p1;
wire  signed [31:0] index_assign_5_2_cas_fu_1216_p1;
wire   [0:0] tmp_33_fu_1220_p3;
wire   [0:0] tmp_32_fu_1208_p3;
wire   [0:0] tmp_31_fu_1196_p3;
wire   [0:0] tmp_30_fu_1182_p3;
wire   [3:0] p_Result_14_3_fu_1228_p5;
wire   [3:0] tmpTmpData_V_1_fu_1240_p2;
wire   [0:0] tmp_34_fu_1246_p1;
wire   [63:0] p_Repl2_4_fu_1250_p1;
wire   [0:0] tmp_36_fu_1264_p3;
reg   [179:0] tmp_35_fu_1254_p4;
wire   [63:0] p_Repl2_4_1_fu_1272_p1;
wire   [0:0] tmp_38_fu_1286_p3;
reg   [179:0] tmp_37_fu_1276_p4;
wire   [63:0] p_Repl2_4_2_fu_1294_p1;
wire   [0:0] tmp_40_fu_1308_p3;
reg   [179:0] tmp_39_fu_1298_p4;
wire   [63:0] p_Repl2_4_3_fu_1316_p1;
wire   [3:0] tmpData_V_fu_1349_p17;
wire   [179:0] tmpData_V_fu_1349_p18;
wire  signed [31:0] tmp_33_cast_fu_1387_p1;
wire   [31:0] index_assign_1_s_fu_1398_p2;
wire  signed [31:0] index_assign_1_1_cas_fu_1412_p1;
wire  signed [31:0] index_assign_1_2_cas_fu_1424_p1;
wire   [0:0] tmp_18_fu_1428_p3;
wire   [0:0] tmp_17_fu_1416_p3;
wire   [0:0] tmp_16_fu_1404_p3;
wire   [0:0] tmp_15_fu_1390_p3;
wire   [3:0] p_Result_12_3_fu_1436_p5;
wire   [3:0] tmpTmpData_V_fu_1448_p2;
wire   [0:0] tmp_19_fu_1454_p1;
wire   [63:0] p_Repl2_2_fu_1458_p1;
wire   [0:0] tmp_22_fu_1472_p3;
reg   [179:0] tmp_20_fu_1462_p4;
wire   [63:0] p_Repl2_2_1_fu_1480_p1;
wire   [0:0] tmp_24_fu_1494_p3;
reg   [179:0] tmp_23_fu_1484_p4;
wire   [63:0] p_Repl2_2_2_fu_1502_p1;
wire   [0:0] tmp_27_fu_1516_p3;
reg   [179:0] tmp_25_fu_1506_p4;
wire   [63:0] p_Repl2_2_3_fu_1524_p1;
reg   [1:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
end

parseEvents_mux_1bkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 180 ),
    .din1_WIDTH( 180 ),
    .din2_WIDTH( 180 ),
    .din3_WIDTH( 180 ),
    .din4_WIDTH( 180 ),
    .din5_WIDTH( 180 ),
    .din6_WIDTH( 180 ),
    .din7_WIDTH( 180 ),
    .din8_WIDTH( 180 ),
    .din9_WIDTH( 180 ),
    .din10_WIDTH( 180 ),
    .din11_WIDTH( 180 ),
    .din12_WIDTH( 180 ),
    .din13_WIDTH( 180 ),
    .din14_WIDTH( 180 ),
    .din15_WIDTH( 180 ),
    .din16_WIDTH( 4 ),
    .dout_WIDTH( 180 ))
parseEvents_mux_1bkb_U1(
    .din0(glPLSlice2_V_0_q0),
    .din1(glPLSlice2_V_1_q0),
    .din2(glPLSlice2_V_2_q0),
    .din3(glPLSlice2_V_3_q0),
    .din4(glPLSlice2_V_4_q0),
    .din5(glPLSlice2_V_5_q0),
    .din6(glPLSlice2_V_6_q0),
    .din7(glPLSlice2_V_7_q0),
    .din8(glPLSlice2_V_8_q0),
    .din9(glPLSlice2_V_9_q0),
    .din10(glPLSlice2_V_10_q0),
    .din11(glPLSlice2_V_11_q0),
    .din12(glPLSlice2_V_12_q0),
    .din13(glPLSlice2_V_13_q0),
    .din14(glPLSlice2_V_14_q0),
    .din15(glPLSlice2_V_15_q0),
    .din16(tmpData_V_2_fu_933_p17),
    .dout(tmpData_V_2_fu_933_p18)
);

parseEvents_mux_1bkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 180 ),
    .din1_WIDTH( 180 ),
    .din2_WIDTH( 180 ),
    .din3_WIDTH( 180 ),
    .din4_WIDTH( 180 ),
    .din5_WIDTH( 180 ),
    .din6_WIDTH( 180 ),
    .din7_WIDTH( 180 ),
    .din8_WIDTH( 180 ),
    .din9_WIDTH( 180 ),
    .din10_WIDTH( 180 ),
    .din11_WIDTH( 180 ),
    .din12_WIDTH( 180 ),
    .din13_WIDTH( 180 ),
    .din14_WIDTH( 180 ),
    .din15_WIDTH( 180 ),
    .din16_WIDTH( 4 ),
    .dout_WIDTH( 180 ))
parseEvents_mux_1bkb_U2(
    .din0(glPLSlice1_V_0_q0),
    .din1(glPLSlice1_V_1_q0),
    .din2(glPLSlice1_V_2_q0),
    .din3(glPLSlice1_V_3_q0),
    .din4(glPLSlice1_V_4_q0),
    .din5(glPLSlice1_V_5_q0),
    .din6(glPLSlice1_V_6_q0),
    .din7(glPLSlice1_V_7_q0),
    .din8(glPLSlice1_V_8_q0),
    .din9(glPLSlice1_V_9_q0),
    .din10(glPLSlice1_V_10_q0),
    .din11(glPLSlice1_V_11_q0),
    .din12(glPLSlice1_V_12_q0),
    .din13(glPLSlice1_V_13_q0),
    .din14(glPLSlice1_V_14_q0),
    .din15(glPLSlice1_V_15_q0),
    .din16(tmpData_V_1_fu_1141_p17),
    .dout(tmpData_V_1_fu_1141_p18)
);

parseEvents_mux_1bkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 180 ),
    .din1_WIDTH( 180 ),
    .din2_WIDTH( 180 ),
    .din3_WIDTH( 180 ),
    .din4_WIDTH( 180 ),
    .din5_WIDTH( 180 ),
    .din6_WIDTH( 180 ),
    .din7_WIDTH( 180 ),
    .din8_WIDTH( 180 ),
    .din9_WIDTH( 180 ),
    .din10_WIDTH( 180 ),
    .din11_WIDTH( 180 ),
    .din12_WIDTH( 180 ),
    .din13_WIDTH( 180 ),
    .din14_WIDTH( 180 ),
    .din15_WIDTH( 180 ),
    .din16_WIDTH( 4 ),
    .dout_WIDTH( 180 ))
parseEvents_mux_1bkb_U3(
    .din0(glPLSlice0_V_0_q0),
    .din1(glPLSlice0_V_1_q0),
    .din2(glPLSlice0_V_2_q0),
    .din3(glPLSlice0_V_3_q0),
    .din4(glPLSlice0_V_4_q0),
    .din5(glPLSlice0_V_5_q0),
    .din6(glPLSlice0_V_6_q0),
    .din7(glPLSlice0_V_7_q0),
    .din8(glPLSlice0_V_8_q0),
    .din9(glPLSlice0_V_9_q0),
    .din10(glPLSlice0_V_10_q0),
    .din11(glPLSlice0_V_11_q0),
    .din12(glPLSlice0_V_12_q0),
    .din13(glPLSlice0_V_13_q0),
    .din14(glPLSlice0_V_14_q0),
    .din15(glPLSlice0_V_15_q0),
    .din16(tmpData_V_fu_1349_p17),
    .dout(tmpData_V_fu_1349_p18)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (tmp_13_fu_852_p2 == 1'd1) & (1'b1 == ap_ce) & (pol_read_read_fu_190_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        glPLSlice0_V_0_addr_reg_1746 <= newIndex3_fu_910_p1;
        glPLSlice0_V_10_addr_reg_1796 <= newIndex3_fu_910_p1;
        glPLSlice0_V_11_addr_reg_1801 <= newIndex3_fu_910_p1;
        glPLSlice0_V_12_addr_reg_1806 <= newIndex3_fu_910_p1;
        glPLSlice0_V_13_addr_reg_1811 <= newIndex3_fu_910_p1;
        glPLSlice0_V_14_addr_reg_1816 <= newIndex3_fu_910_p1;
        glPLSlice0_V_15_addr_reg_1821 <= newIndex3_fu_910_p1;
        glPLSlice0_V_1_addr_reg_1751 <= newIndex3_fu_910_p1;
        glPLSlice0_V_2_addr_reg_1756 <= newIndex3_fu_910_p1;
        glPLSlice0_V_3_addr_reg_1761 <= newIndex3_fu_910_p1;
        glPLSlice0_V_4_addr_reg_1766 <= newIndex3_fu_910_p1;
        glPLSlice0_V_5_addr_reg_1771 <= newIndex3_fu_910_p1;
        glPLSlice0_V_6_addr_reg_1776 <= newIndex3_fu_910_p1;
        glPLSlice0_V_7_addr_reg_1781 <= newIndex3_fu_910_p1;
        glPLSlice0_V_8_addr_reg_1786 <= newIndex3_fu_910_p1;
        glPLSlice0_V_9_addr_reg_1791 <= newIndex3_fu_910_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (tmp_21_fu_858_p2 == 1'd1) & (tmp_13_fu_852_p2 == 1'd0) & (1'b1 == ap_ce) & (pol_read_read_fu_190_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        glPLSlice1_V_0_addr_reg_1666 <= newIndex5_fu_890_p1;
        glPLSlice1_V_10_addr_reg_1716 <= newIndex5_fu_890_p1;
        glPLSlice1_V_11_addr_reg_1721 <= newIndex5_fu_890_p1;
        glPLSlice1_V_12_addr_reg_1726 <= newIndex5_fu_890_p1;
        glPLSlice1_V_13_addr_reg_1731 <= newIndex5_fu_890_p1;
        glPLSlice1_V_14_addr_reg_1736 <= newIndex5_fu_890_p1;
        glPLSlice1_V_15_addr_reg_1741 <= newIndex5_fu_890_p1;
        glPLSlice1_V_1_addr_reg_1671 <= newIndex5_fu_890_p1;
        glPLSlice1_V_2_addr_reg_1676 <= newIndex5_fu_890_p1;
        glPLSlice1_V_3_addr_reg_1681 <= newIndex5_fu_890_p1;
        glPLSlice1_V_4_addr_reg_1686 <= newIndex5_fu_890_p1;
        glPLSlice1_V_5_addr_reg_1691 <= newIndex5_fu_890_p1;
        glPLSlice1_V_6_addr_reg_1696 <= newIndex5_fu_890_p1;
        glPLSlice1_V_7_addr_reg_1701 <= newIndex5_fu_890_p1;
        glPLSlice1_V_8_addr_reg_1706 <= newIndex5_fu_890_p1;
        glPLSlice1_V_9_addr_reg_1711 <= newIndex5_fu_890_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (tmp_21_fu_858_p2 == 1'd0) & (tmp_26_fu_864_p2 == 1'd1) & (tmp_13_fu_852_p2 == 1'd0) & (1'b1 == ap_ce) & (pol_read_read_fu_190_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        glPLSlice2_V_0_addr_reg_1586 <= newIndex6_fu_870_p1;
        glPLSlice2_V_10_addr_reg_1636 <= newIndex6_fu_870_p1;
        glPLSlice2_V_11_addr_reg_1641 <= newIndex6_fu_870_p1;
        glPLSlice2_V_12_addr_reg_1646 <= newIndex6_fu_870_p1;
        glPLSlice2_V_13_addr_reg_1651 <= newIndex6_fu_870_p1;
        glPLSlice2_V_14_addr_reg_1656 <= newIndex6_fu_870_p1;
        glPLSlice2_V_15_addr_reg_1661 <= newIndex6_fu_870_p1;
        glPLSlice2_V_1_addr_reg_1591 <= newIndex6_fu_870_p1;
        glPLSlice2_V_2_addr_reg_1596 <= newIndex6_fu_870_p1;
        glPLSlice2_V_3_addr_reg_1601 <= newIndex6_fu_870_p1;
        glPLSlice2_V_4_addr_reg_1606 <= newIndex6_fu_870_p1;
        glPLSlice2_V_5_addr_reg_1611 <= newIndex6_fu_870_p1;
        glPLSlice2_V_6_addr_reg_1616 <= newIndex6_fu_870_p1;
        glPLSlice2_V_7_addr_reg_1621 <= newIndex6_fu_870_p1;
        glPLSlice2_V_8_addr_reg_1626 <= newIndex6_fu_870_p1;
        glPLSlice2_V_9_addr_reg_1631 <= newIndex6_fu_870_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1))) begin
        pol_read_reg_1554 <= pol;
        tmp_12_reg_1558[8 : 2] <= tmp_12_fu_823_p3[8 : 2];
        xNewIdx_V_reg_1567 <= xNewIdx_V_fu_841_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_ce) & (pol_read_read_fu_190_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        tmp_13_reg_1574 <= tmp_13_fu_852_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (tmp_13_fu_852_p2 == 1'd0) & (1'b1 == ap_ce) & (pol_read_read_fu_190_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        tmp_21_reg_1578 <= tmp_21_fu_858_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (tmp_21_fu_858_p2 == 1'd0) & (tmp_13_fu_852_p2 == 1'd0) & (1'b1 == ap_ce) & (pol_read_read_fu_190_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        tmp_26_reg_1582 <= tmp_26_fu_864_p2;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlice0_V_0_address0 = glPLSlice0_V_0_addr_reg_1746;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        glPLSlice0_V_0_address0 = newIndex3_fu_910_p1;
    end else begin
        glPLSlice0_V_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        glPLSlice0_V_0_ce0 = 1'b1;
    end else begin
        glPLSlice0_V_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_14_fu_1346_p1 == 4'd0) & (tmp_13_reg_1574 == 1'd1) & (1'b1 == ap_ce) & (pol_read_reg_1554 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlice0_V_0_we0 = 1'b1;
    end else begin
        glPLSlice0_V_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlice0_V_10_address0 = glPLSlice0_V_10_addr_reg_1796;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        glPLSlice0_V_10_address0 = newIndex3_fu_910_p1;
    end else begin
        glPLSlice0_V_10_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        glPLSlice0_V_10_ce0 = 1'b1;
    end else begin
        glPLSlice0_V_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_14_fu_1346_p1 == 4'd10) & (tmp_13_reg_1574 == 1'd1) & (1'b1 == ap_ce) & (pol_read_reg_1554 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlice0_V_10_we0 = 1'b1;
    end else begin
        glPLSlice0_V_10_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlice0_V_11_address0 = glPLSlice0_V_11_addr_reg_1801;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        glPLSlice0_V_11_address0 = newIndex3_fu_910_p1;
    end else begin
        glPLSlice0_V_11_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        glPLSlice0_V_11_ce0 = 1'b1;
    end else begin
        glPLSlice0_V_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_14_fu_1346_p1 == 4'd11) & (tmp_13_reg_1574 == 1'd1) & (1'b1 == ap_ce) & (pol_read_reg_1554 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlice0_V_11_we0 = 1'b1;
    end else begin
        glPLSlice0_V_11_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlice0_V_12_address0 = glPLSlice0_V_12_addr_reg_1806;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        glPLSlice0_V_12_address0 = newIndex3_fu_910_p1;
    end else begin
        glPLSlice0_V_12_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        glPLSlice0_V_12_ce0 = 1'b1;
    end else begin
        glPLSlice0_V_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_14_fu_1346_p1 == 4'd12) & (tmp_13_reg_1574 == 1'd1) & (1'b1 == ap_ce) & (pol_read_reg_1554 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlice0_V_12_we0 = 1'b1;
    end else begin
        glPLSlice0_V_12_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlice0_V_13_address0 = glPLSlice0_V_13_addr_reg_1811;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        glPLSlice0_V_13_address0 = newIndex3_fu_910_p1;
    end else begin
        glPLSlice0_V_13_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        glPLSlice0_V_13_ce0 = 1'b1;
    end else begin
        glPLSlice0_V_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_14_fu_1346_p1 == 4'd13) & (tmp_13_reg_1574 == 1'd1) & (1'b1 == ap_ce) & (pol_read_reg_1554 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlice0_V_13_we0 = 1'b1;
    end else begin
        glPLSlice0_V_13_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlice0_V_14_address0 = glPLSlice0_V_14_addr_reg_1816;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        glPLSlice0_V_14_address0 = newIndex3_fu_910_p1;
    end else begin
        glPLSlice0_V_14_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        glPLSlice0_V_14_ce0 = 1'b1;
    end else begin
        glPLSlice0_V_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_14_fu_1346_p1 == 4'd14) & (tmp_13_reg_1574 == 1'd1) & (1'b1 == ap_ce) & (pol_read_reg_1554 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlice0_V_14_we0 = 1'b1;
    end else begin
        glPLSlice0_V_14_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlice0_V_15_address0 = glPLSlice0_V_15_addr_reg_1821;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        glPLSlice0_V_15_address0 = newIndex3_fu_910_p1;
    end else begin
        glPLSlice0_V_15_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        glPLSlice0_V_15_ce0 = 1'b1;
    end else begin
        glPLSlice0_V_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_14_fu_1346_p1 == 4'd15) & (tmp_13_reg_1574 == 1'd1) & (1'b1 == ap_ce) & (pol_read_reg_1554 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlice0_V_15_we0 = 1'b1;
    end else begin
        glPLSlice0_V_15_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlice0_V_1_address0 = glPLSlice0_V_1_addr_reg_1751;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        glPLSlice0_V_1_address0 = newIndex3_fu_910_p1;
    end else begin
        glPLSlice0_V_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        glPLSlice0_V_1_ce0 = 1'b1;
    end else begin
        glPLSlice0_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_14_fu_1346_p1 == 4'd1) & (tmp_13_reg_1574 == 1'd1) & (1'b1 == ap_ce) & (pol_read_reg_1554 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlice0_V_1_we0 = 1'b1;
    end else begin
        glPLSlice0_V_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlice0_V_2_address0 = glPLSlice0_V_2_addr_reg_1756;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        glPLSlice0_V_2_address0 = newIndex3_fu_910_p1;
    end else begin
        glPLSlice0_V_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        glPLSlice0_V_2_ce0 = 1'b1;
    end else begin
        glPLSlice0_V_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_14_fu_1346_p1 == 4'd2) & (tmp_13_reg_1574 == 1'd1) & (1'b1 == ap_ce) & (pol_read_reg_1554 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlice0_V_2_we0 = 1'b1;
    end else begin
        glPLSlice0_V_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlice0_V_3_address0 = glPLSlice0_V_3_addr_reg_1761;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        glPLSlice0_V_3_address0 = newIndex3_fu_910_p1;
    end else begin
        glPLSlice0_V_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        glPLSlice0_V_3_ce0 = 1'b1;
    end else begin
        glPLSlice0_V_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_14_fu_1346_p1 == 4'd3) & (tmp_13_reg_1574 == 1'd1) & (1'b1 == ap_ce) & (pol_read_reg_1554 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlice0_V_3_we0 = 1'b1;
    end else begin
        glPLSlice0_V_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlice0_V_4_address0 = glPLSlice0_V_4_addr_reg_1766;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        glPLSlice0_V_4_address0 = newIndex3_fu_910_p1;
    end else begin
        glPLSlice0_V_4_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        glPLSlice0_V_4_ce0 = 1'b1;
    end else begin
        glPLSlice0_V_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_14_fu_1346_p1 == 4'd4) & (tmp_13_reg_1574 == 1'd1) & (1'b1 == ap_ce) & (pol_read_reg_1554 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlice0_V_4_we0 = 1'b1;
    end else begin
        glPLSlice0_V_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlice0_V_5_address0 = glPLSlice0_V_5_addr_reg_1771;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        glPLSlice0_V_5_address0 = newIndex3_fu_910_p1;
    end else begin
        glPLSlice0_V_5_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        glPLSlice0_V_5_ce0 = 1'b1;
    end else begin
        glPLSlice0_V_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_14_fu_1346_p1 == 4'd5) & (tmp_13_reg_1574 == 1'd1) & (1'b1 == ap_ce) & (pol_read_reg_1554 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlice0_V_5_we0 = 1'b1;
    end else begin
        glPLSlice0_V_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlice0_V_6_address0 = glPLSlice0_V_6_addr_reg_1776;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        glPLSlice0_V_6_address0 = newIndex3_fu_910_p1;
    end else begin
        glPLSlice0_V_6_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        glPLSlice0_V_6_ce0 = 1'b1;
    end else begin
        glPLSlice0_V_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_14_fu_1346_p1 == 4'd6) & (tmp_13_reg_1574 == 1'd1) & (1'b1 == ap_ce) & (pol_read_reg_1554 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlice0_V_6_we0 = 1'b1;
    end else begin
        glPLSlice0_V_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlice0_V_7_address0 = glPLSlice0_V_7_addr_reg_1781;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        glPLSlice0_V_7_address0 = newIndex3_fu_910_p1;
    end else begin
        glPLSlice0_V_7_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        glPLSlice0_V_7_ce0 = 1'b1;
    end else begin
        glPLSlice0_V_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_14_fu_1346_p1 == 4'd7) & (tmp_13_reg_1574 == 1'd1) & (1'b1 == ap_ce) & (pol_read_reg_1554 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlice0_V_7_we0 = 1'b1;
    end else begin
        glPLSlice0_V_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlice0_V_8_address0 = glPLSlice0_V_8_addr_reg_1786;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        glPLSlice0_V_8_address0 = newIndex3_fu_910_p1;
    end else begin
        glPLSlice0_V_8_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        glPLSlice0_V_8_ce0 = 1'b1;
    end else begin
        glPLSlice0_V_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_14_fu_1346_p1 == 4'd8) & (tmp_13_reg_1574 == 1'd1) & (1'b1 == ap_ce) & (pol_read_reg_1554 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlice0_V_8_we0 = 1'b1;
    end else begin
        glPLSlice0_V_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlice0_V_9_address0 = glPLSlice0_V_9_addr_reg_1791;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        glPLSlice0_V_9_address0 = newIndex3_fu_910_p1;
    end else begin
        glPLSlice0_V_9_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        glPLSlice0_V_9_ce0 = 1'b1;
    end else begin
        glPLSlice0_V_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_14_fu_1346_p1 == 4'd9) & (tmp_13_reg_1574 == 1'd1) & (1'b1 == ap_ce) & (pol_read_reg_1554 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlice0_V_9_we0 = 1'b1;
    end else begin
        glPLSlice0_V_9_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlice1_V_0_address0 = glPLSlice1_V_0_addr_reg_1666;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        glPLSlice1_V_0_address0 = newIndex5_fu_890_p1;
    end else begin
        glPLSlice1_V_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        glPLSlice1_V_0_ce0 = 1'b1;
    end else begin
        glPLSlice1_V_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_29_fu_1138_p1 == 4'd0) & (tmp_21_reg_1578 == 1'd1) & (tmp_13_reg_1574 == 1'd0) & (1'b1 == ap_ce) & (pol_read_reg_1554 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlice1_V_0_we0 = 1'b1;
    end else begin
        glPLSlice1_V_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlice1_V_10_address0 = glPLSlice1_V_10_addr_reg_1716;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        glPLSlice1_V_10_address0 = newIndex5_fu_890_p1;
    end else begin
        glPLSlice1_V_10_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        glPLSlice1_V_10_ce0 = 1'b1;
    end else begin
        glPLSlice1_V_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_29_fu_1138_p1 == 4'd10) & (tmp_21_reg_1578 == 1'd1) & (tmp_13_reg_1574 == 1'd0) & (1'b1 == ap_ce) & (pol_read_reg_1554 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlice1_V_10_we0 = 1'b1;
    end else begin
        glPLSlice1_V_10_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlice1_V_11_address0 = glPLSlice1_V_11_addr_reg_1721;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        glPLSlice1_V_11_address0 = newIndex5_fu_890_p1;
    end else begin
        glPLSlice1_V_11_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        glPLSlice1_V_11_ce0 = 1'b1;
    end else begin
        glPLSlice1_V_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_29_fu_1138_p1 == 4'd11) & (tmp_21_reg_1578 == 1'd1) & (tmp_13_reg_1574 == 1'd0) & (1'b1 == ap_ce) & (pol_read_reg_1554 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlice1_V_11_we0 = 1'b1;
    end else begin
        glPLSlice1_V_11_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlice1_V_12_address0 = glPLSlice1_V_12_addr_reg_1726;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        glPLSlice1_V_12_address0 = newIndex5_fu_890_p1;
    end else begin
        glPLSlice1_V_12_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        glPLSlice1_V_12_ce0 = 1'b1;
    end else begin
        glPLSlice1_V_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_29_fu_1138_p1 == 4'd12) & (tmp_21_reg_1578 == 1'd1) & (tmp_13_reg_1574 == 1'd0) & (1'b1 == ap_ce) & (pol_read_reg_1554 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlice1_V_12_we0 = 1'b1;
    end else begin
        glPLSlice1_V_12_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlice1_V_13_address0 = glPLSlice1_V_13_addr_reg_1731;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        glPLSlice1_V_13_address0 = newIndex5_fu_890_p1;
    end else begin
        glPLSlice1_V_13_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        glPLSlice1_V_13_ce0 = 1'b1;
    end else begin
        glPLSlice1_V_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_29_fu_1138_p1 == 4'd13) & (tmp_21_reg_1578 == 1'd1) & (tmp_13_reg_1574 == 1'd0) & (1'b1 == ap_ce) & (pol_read_reg_1554 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlice1_V_13_we0 = 1'b1;
    end else begin
        glPLSlice1_V_13_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlice1_V_14_address0 = glPLSlice1_V_14_addr_reg_1736;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        glPLSlice1_V_14_address0 = newIndex5_fu_890_p1;
    end else begin
        glPLSlice1_V_14_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        glPLSlice1_V_14_ce0 = 1'b1;
    end else begin
        glPLSlice1_V_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_29_fu_1138_p1 == 4'd14) & (tmp_21_reg_1578 == 1'd1) & (tmp_13_reg_1574 == 1'd0) & (1'b1 == ap_ce) & (pol_read_reg_1554 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlice1_V_14_we0 = 1'b1;
    end else begin
        glPLSlice1_V_14_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlice1_V_15_address0 = glPLSlice1_V_15_addr_reg_1741;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        glPLSlice1_V_15_address0 = newIndex5_fu_890_p1;
    end else begin
        glPLSlice1_V_15_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        glPLSlice1_V_15_ce0 = 1'b1;
    end else begin
        glPLSlice1_V_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_29_fu_1138_p1 == 4'd15) & (tmp_21_reg_1578 == 1'd1) & (tmp_13_reg_1574 == 1'd0) & (1'b1 == ap_ce) & (pol_read_reg_1554 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlice1_V_15_we0 = 1'b1;
    end else begin
        glPLSlice1_V_15_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlice1_V_1_address0 = glPLSlice1_V_1_addr_reg_1671;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        glPLSlice1_V_1_address0 = newIndex5_fu_890_p1;
    end else begin
        glPLSlice1_V_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        glPLSlice1_V_1_ce0 = 1'b1;
    end else begin
        glPLSlice1_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_29_fu_1138_p1 == 4'd1) & (tmp_21_reg_1578 == 1'd1) & (tmp_13_reg_1574 == 1'd0) & (1'b1 == ap_ce) & (pol_read_reg_1554 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlice1_V_1_we0 = 1'b1;
    end else begin
        glPLSlice1_V_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlice1_V_2_address0 = glPLSlice1_V_2_addr_reg_1676;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        glPLSlice1_V_2_address0 = newIndex5_fu_890_p1;
    end else begin
        glPLSlice1_V_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        glPLSlice1_V_2_ce0 = 1'b1;
    end else begin
        glPLSlice1_V_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_29_fu_1138_p1 == 4'd2) & (tmp_21_reg_1578 == 1'd1) & (tmp_13_reg_1574 == 1'd0) & (1'b1 == ap_ce) & (pol_read_reg_1554 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlice1_V_2_we0 = 1'b1;
    end else begin
        glPLSlice1_V_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlice1_V_3_address0 = glPLSlice1_V_3_addr_reg_1681;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        glPLSlice1_V_3_address0 = newIndex5_fu_890_p1;
    end else begin
        glPLSlice1_V_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        glPLSlice1_V_3_ce0 = 1'b1;
    end else begin
        glPLSlice1_V_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_29_fu_1138_p1 == 4'd3) & (tmp_21_reg_1578 == 1'd1) & (tmp_13_reg_1574 == 1'd0) & (1'b1 == ap_ce) & (pol_read_reg_1554 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlice1_V_3_we0 = 1'b1;
    end else begin
        glPLSlice1_V_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlice1_V_4_address0 = glPLSlice1_V_4_addr_reg_1686;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        glPLSlice1_V_4_address0 = newIndex5_fu_890_p1;
    end else begin
        glPLSlice1_V_4_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        glPLSlice1_V_4_ce0 = 1'b1;
    end else begin
        glPLSlice1_V_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_29_fu_1138_p1 == 4'd4) & (tmp_21_reg_1578 == 1'd1) & (tmp_13_reg_1574 == 1'd0) & (1'b1 == ap_ce) & (pol_read_reg_1554 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlice1_V_4_we0 = 1'b1;
    end else begin
        glPLSlice1_V_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlice1_V_5_address0 = glPLSlice1_V_5_addr_reg_1691;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        glPLSlice1_V_5_address0 = newIndex5_fu_890_p1;
    end else begin
        glPLSlice1_V_5_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        glPLSlice1_V_5_ce0 = 1'b1;
    end else begin
        glPLSlice1_V_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_29_fu_1138_p1 == 4'd5) & (tmp_21_reg_1578 == 1'd1) & (tmp_13_reg_1574 == 1'd0) & (1'b1 == ap_ce) & (pol_read_reg_1554 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlice1_V_5_we0 = 1'b1;
    end else begin
        glPLSlice1_V_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlice1_V_6_address0 = glPLSlice1_V_6_addr_reg_1696;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        glPLSlice1_V_6_address0 = newIndex5_fu_890_p1;
    end else begin
        glPLSlice1_V_6_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        glPLSlice1_V_6_ce0 = 1'b1;
    end else begin
        glPLSlice1_V_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_29_fu_1138_p1 == 4'd6) & (tmp_21_reg_1578 == 1'd1) & (tmp_13_reg_1574 == 1'd0) & (1'b1 == ap_ce) & (pol_read_reg_1554 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlice1_V_6_we0 = 1'b1;
    end else begin
        glPLSlice1_V_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlice1_V_7_address0 = glPLSlice1_V_7_addr_reg_1701;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        glPLSlice1_V_7_address0 = newIndex5_fu_890_p1;
    end else begin
        glPLSlice1_V_7_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        glPLSlice1_V_7_ce0 = 1'b1;
    end else begin
        glPLSlice1_V_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_29_fu_1138_p1 == 4'd7) & (tmp_21_reg_1578 == 1'd1) & (tmp_13_reg_1574 == 1'd0) & (1'b1 == ap_ce) & (pol_read_reg_1554 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlice1_V_7_we0 = 1'b1;
    end else begin
        glPLSlice1_V_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlice1_V_8_address0 = glPLSlice1_V_8_addr_reg_1706;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        glPLSlice1_V_8_address0 = newIndex5_fu_890_p1;
    end else begin
        glPLSlice1_V_8_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        glPLSlice1_V_8_ce0 = 1'b1;
    end else begin
        glPLSlice1_V_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_29_fu_1138_p1 == 4'd8) & (tmp_21_reg_1578 == 1'd1) & (tmp_13_reg_1574 == 1'd0) & (1'b1 == ap_ce) & (pol_read_reg_1554 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlice1_V_8_we0 = 1'b1;
    end else begin
        glPLSlice1_V_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlice1_V_9_address0 = glPLSlice1_V_9_addr_reg_1711;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        glPLSlice1_V_9_address0 = newIndex5_fu_890_p1;
    end else begin
        glPLSlice1_V_9_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        glPLSlice1_V_9_ce0 = 1'b1;
    end else begin
        glPLSlice1_V_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_29_fu_1138_p1 == 4'd9) & (tmp_21_reg_1578 == 1'd1) & (tmp_13_reg_1574 == 1'd0) & (1'b1 == ap_ce) & (pol_read_reg_1554 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlice1_V_9_we0 = 1'b1;
    end else begin
        glPLSlice1_V_9_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlice2_V_0_address0 = glPLSlice2_V_0_addr_reg_1586;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        glPLSlice2_V_0_address0 = newIndex6_fu_870_p1;
    end else begin
        glPLSlice2_V_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        glPLSlice2_V_0_ce0 = 1'b1;
    end else begin
        glPLSlice2_V_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_42_fu_930_p1 == 4'd0) & (tmp_21_reg_1578 == 1'd0) & (tmp_26_reg_1582 == 1'd1) & (tmp_13_reg_1574 == 1'd0) & (1'b1 == ap_ce) & (pol_read_reg_1554 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlice2_V_0_we0 = 1'b1;
    end else begin
        glPLSlice2_V_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlice2_V_10_address0 = glPLSlice2_V_10_addr_reg_1636;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        glPLSlice2_V_10_address0 = newIndex6_fu_870_p1;
    end else begin
        glPLSlice2_V_10_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        glPLSlice2_V_10_ce0 = 1'b1;
    end else begin
        glPLSlice2_V_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_42_fu_930_p1 == 4'd10) & (tmp_21_reg_1578 == 1'd0) & (tmp_26_reg_1582 == 1'd1) & (tmp_13_reg_1574 == 1'd0) & (1'b1 == ap_ce) & (pol_read_reg_1554 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlice2_V_10_we0 = 1'b1;
    end else begin
        glPLSlice2_V_10_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlice2_V_11_address0 = glPLSlice2_V_11_addr_reg_1641;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        glPLSlice2_V_11_address0 = newIndex6_fu_870_p1;
    end else begin
        glPLSlice2_V_11_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        glPLSlice2_V_11_ce0 = 1'b1;
    end else begin
        glPLSlice2_V_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_42_fu_930_p1 == 4'd11) & (tmp_21_reg_1578 == 1'd0) & (tmp_26_reg_1582 == 1'd1) & (tmp_13_reg_1574 == 1'd0) & (1'b1 == ap_ce) & (pol_read_reg_1554 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlice2_V_11_we0 = 1'b1;
    end else begin
        glPLSlice2_V_11_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlice2_V_12_address0 = glPLSlice2_V_12_addr_reg_1646;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        glPLSlice2_V_12_address0 = newIndex6_fu_870_p1;
    end else begin
        glPLSlice2_V_12_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        glPLSlice2_V_12_ce0 = 1'b1;
    end else begin
        glPLSlice2_V_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_42_fu_930_p1 == 4'd12) & (tmp_21_reg_1578 == 1'd0) & (tmp_26_reg_1582 == 1'd1) & (tmp_13_reg_1574 == 1'd0) & (1'b1 == ap_ce) & (pol_read_reg_1554 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlice2_V_12_we0 = 1'b1;
    end else begin
        glPLSlice2_V_12_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlice2_V_13_address0 = glPLSlice2_V_13_addr_reg_1651;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        glPLSlice2_V_13_address0 = newIndex6_fu_870_p1;
    end else begin
        glPLSlice2_V_13_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        glPLSlice2_V_13_ce0 = 1'b1;
    end else begin
        glPLSlice2_V_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_42_fu_930_p1 == 4'd13) & (tmp_21_reg_1578 == 1'd0) & (tmp_26_reg_1582 == 1'd1) & (tmp_13_reg_1574 == 1'd0) & (1'b1 == ap_ce) & (pol_read_reg_1554 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlice2_V_13_we0 = 1'b1;
    end else begin
        glPLSlice2_V_13_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlice2_V_14_address0 = glPLSlice2_V_14_addr_reg_1656;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        glPLSlice2_V_14_address0 = newIndex6_fu_870_p1;
    end else begin
        glPLSlice2_V_14_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        glPLSlice2_V_14_ce0 = 1'b1;
    end else begin
        glPLSlice2_V_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_42_fu_930_p1 == 4'd14) & (tmp_21_reg_1578 == 1'd0) & (tmp_26_reg_1582 == 1'd1) & (tmp_13_reg_1574 == 1'd0) & (1'b1 == ap_ce) & (pol_read_reg_1554 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlice2_V_14_we0 = 1'b1;
    end else begin
        glPLSlice2_V_14_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlice2_V_15_address0 = glPLSlice2_V_15_addr_reg_1661;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        glPLSlice2_V_15_address0 = newIndex6_fu_870_p1;
    end else begin
        glPLSlice2_V_15_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        glPLSlice2_V_15_ce0 = 1'b1;
    end else begin
        glPLSlice2_V_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_42_fu_930_p1 == 4'd15) & (tmp_21_reg_1578 == 1'd0) & (tmp_26_reg_1582 == 1'd1) & (tmp_13_reg_1574 == 1'd0) & (1'b1 == ap_ce) & (pol_read_reg_1554 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlice2_V_15_we0 = 1'b1;
    end else begin
        glPLSlice2_V_15_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlice2_V_1_address0 = glPLSlice2_V_1_addr_reg_1591;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        glPLSlice2_V_1_address0 = newIndex6_fu_870_p1;
    end else begin
        glPLSlice2_V_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        glPLSlice2_V_1_ce0 = 1'b1;
    end else begin
        glPLSlice2_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_42_fu_930_p1 == 4'd1) & (tmp_21_reg_1578 == 1'd0) & (tmp_26_reg_1582 == 1'd1) & (tmp_13_reg_1574 == 1'd0) & (1'b1 == ap_ce) & (pol_read_reg_1554 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlice2_V_1_we0 = 1'b1;
    end else begin
        glPLSlice2_V_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlice2_V_2_address0 = glPLSlice2_V_2_addr_reg_1596;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        glPLSlice2_V_2_address0 = newIndex6_fu_870_p1;
    end else begin
        glPLSlice2_V_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        glPLSlice2_V_2_ce0 = 1'b1;
    end else begin
        glPLSlice2_V_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_42_fu_930_p1 == 4'd2) & (tmp_21_reg_1578 == 1'd0) & (tmp_26_reg_1582 == 1'd1) & (tmp_13_reg_1574 == 1'd0) & (1'b1 == ap_ce) & (pol_read_reg_1554 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlice2_V_2_we0 = 1'b1;
    end else begin
        glPLSlice2_V_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlice2_V_3_address0 = glPLSlice2_V_3_addr_reg_1601;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        glPLSlice2_V_3_address0 = newIndex6_fu_870_p1;
    end else begin
        glPLSlice2_V_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        glPLSlice2_V_3_ce0 = 1'b1;
    end else begin
        glPLSlice2_V_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_42_fu_930_p1 == 4'd3) & (tmp_21_reg_1578 == 1'd0) & (tmp_26_reg_1582 == 1'd1) & (tmp_13_reg_1574 == 1'd0) & (1'b1 == ap_ce) & (pol_read_reg_1554 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlice2_V_3_we0 = 1'b1;
    end else begin
        glPLSlice2_V_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlice2_V_4_address0 = glPLSlice2_V_4_addr_reg_1606;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        glPLSlice2_V_4_address0 = newIndex6_fu_870_p1;
    end else begin
        glPLSlice2_V_4_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        glPLSlice2_V_4_ce0 = 1'b1;
    end else begin
        glPLSlice2_V_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_42_fu_930_p1 == 4'd4) & (tmp_21_reg_1578 == 1'd0) & (tmp_26_reg_1582 == 1'd1) & (tmp_13_reg_1574 == 1'd0) & (1'b1 == ap_ce) & (pol_read_reg_1554 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlice2_V_4_we0 = 1'b1;
    end else begin
        glPLSlice2_V_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlice2_V_5_address0 = glPLSlice2_V_5_addr_reg_1611;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        glPLSlice2_V_5_address0 = newIndex6_fu_870_p1;
    end else begin
        glPLSlice2_V_5_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        glPLSlice2_V_5_ce0 = 1'b1;
    end else begin
        glPLSlice2_V_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_42_fu_930_p1 == 4'd5) & (tmp_21_reg_1578 == 1'd0) & (tmp_26_reg_1582 == 1'd1) & (tmp_13_reg_1574 == 1'd0) & (1'b1 == ap_ce) & (pol_read_reg_1554 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlice2_V_5_we0 = 1'b1;
    end else begin
        glPLSlice2_V_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlice2_V_6_address0 = glPLSlice2_V_6_addr_reg_1616;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        glPLSlice2_V_6_address0 = newIndex6_fu_870_p1;
    end else begin
        glPLSlice2_V_6_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        glPLSlice2_V_6_ce0 = 1'b1;
    end else begin
        glPLSlice2_V_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_42_fu_930_p1 == 4'd6) & (tmp_21_reg_1578 == 1'd0) & (tmp_26_reg_1582 == 1'd1) & (tmp_13_reg_1574 == 1'd0) & (1'b1 == ap_ce) & (pol_read_reg_1554 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlice2_V_6_we0 = 1'b1;
    end else begin
        glPLSlice2_V_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlice2_V_7_address0 = glPLSlice2_V_7_addr_reg_1621;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        glPLSlice2_V_7_address0 = newIndex6_fu_870_p1;
    end else begin
        glPLSlice2_V_7_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        glPLSlice2_V_7_ce0 = 1'b1;
    end else begin
        glPLSlice2_V_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_42_fu_930_p1 == 4'd7) & (tmp_21_reg_1578 == 1'd0) & (tmp_26_reg_1582 == 1'd1) & (tmp_13_reg_1574 == 1'd0) & (1'b1 == ap_ce) & (pol_read_reg_1554 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlice2_V_7_we0 = 1'b1;
    end else begin
        glPLSlice2_V_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlice2_V_8_address0 = glPLSlice2_V_8_addr_reg_1626;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        glPLSlice2_V_8_address0 = newIndex6_fu_870_p1;
    end else begin
        glPLSlice2_V_8_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        glPLSlice2_V_8_ce0 = 1'b1;
    end else begin
        glPLSlice2_V_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_42_fu_930_p1 == 4'd8) & (tmp_21_reg_1578 == 1'd0) & (tmp_26_reg_1582 == 1'd1) & (tmp_13_reg_1574 == 1'd0) & (1'b1 == ap_ce) & (pol_read_reg_1554 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlice2_V_8_we0 = 1'b1;
    end else begin
        glPLSlice2_V_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlice2_V_9_address0 = glPLSlice2_V_9_addr_reg_1631;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        glPLSlice2_V_9_address0 = newIndex6_fu_870_p1;
    end else begin
        glPLSlice2_V_9_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        glPLSlice2_V_9_ce0 = 1'b1;
    end else begin
        glPLSlice2_V_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_42_fu_930_p1 == 4'd9) & (tmp_21_reg_1578 == 1'd0) & (tmp_26_reg_1582 == 1'd1) & (tmp_13_reg_1574 == 1'd0) & (1'b1 == ap_ce) & (pol_read_reg_1554 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlice2_V_9_we0 = 1'b1;
    end else begin
        glPLSlice2_V_9_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign glPLSlice0_V_0_d0 = tmp_28_fu_1528_p4;

assign glPLSlice0_V_10_d0 = tmp_28_fu_1528_p4;

assign glPLSlice0_V_11_d0 = tmp_28_fu_1528_p4;

assign glPLSlice0_V_12_d0 = tmp_28_fu_1528_p4;

assign glPLSlice0_V_13_d0 = tmp_28_fu_1528_p4;

assign glPLSlice0_V_14_d0 = tmp_28_fu_1528_p4;

assign glPLSlice0_V_15_d0 = tmp_28_fu_1528_p4;

assign glPLSlice0_V_1_d0 = tmp_28_fu_1528_p4;

assign glPLSlice0_V_2_d0 = tmp_28_fu_1528_p4;

assign glPLSlice0_V_3_d0 = tmp_28_fu_1528_p4;

assign glPLSlice0_V_4_d0 = tmp_28_fu_1528_p4;

assign glPLSlice0_V_5_d0 = tmp_28_fu_1528_p4;

assign glPLSlice0_V_6_d0 = tmp_28_fu_1528_p4;

assign glPLSlice0_V_7_d0 = tmp_28_fu_1528_p4;

assign glPLSlice0_V_8_d0 = tmp_28_fu_1528_p4;

assign glPLSlice0_V_9_d0 = tmp_28_fu_1528_p4;

assign glPLSlice1_V_0_d0 = tmp_41_fu_1320_p4;

assign glPLSlice1_V_10_d0 = tmp_41_fu_1320_p4;

assign glPLSlice1_V_11_d0 = tmp_41_fu_1320_p4;

assign glPLSlice1_V_12_d0 = tmp_41_fu_1320_p4;

assign glPLSlice1_V_13_d0 = tmp_41_fu_1320_p4;

assign glPLSlice1_V_14_d0 = tmp_41_fu_1320_p4;

assign glPLSlice1_V_15_d0 = tmp_41_fu_1320_p4;

assign glPLSlice1_V_1_d0 = tmp_41_fu_1320_p4;

assign glPLSlice1_V_2_d0 = tmp_41_fu_1320_p4;

assign glPLSlice1_V_3_d0 = tmp_41_fu_1320_p4;

assign glPLSlice1_V_4_d0 = tmp_41_fu_1320_p4;

assign glPLSlice1_V_5_d0 = tmp_41_fu_1320_p4;

assign glPLSlice1_V_6_d0 = tmp_41_fu_1320_p4;

assign glPLSlice1_V_7_d0 = tmp_41_fu_1320_p4;

assign glPLSlice1_V_8_d0 = tmp_41_fu_1320_p4;

assign glPLSlice1_V_9_d0 = tmp_41_fu_1320_p4;

assign glPLSlice2_V_0_d0 = tmp_54_fu_1112_p4;

assign glPLSlice2_V_10_d0 = tmp_54_fu_1112_p4;

assign glPLSlice2_V_11_d0 = tmp_54_fu_1112_p4;

assign glPLSlice2_V_12_d0 = tmp_54_fu_1112_p4;

assign glPLSlice2_V_13_d0 = tmp_54_fu_1112_p4;

assign glPLSlice2_V_14_d0 = tmp_54_fu_1112_p4;

assign glPLSlice2_V_15_d0 = tmp_54_fu_1112_p4;

assign glPLSlice2_V_1_d0 = tmp_54_fu_1112_p4;

assign glPLSlice2_V_2_d0 = tmp_54_fu_1112_p4;

assign glPLSlice2_V_3_d0 = tmp_54_fu_1112_p4;

assign glPLSlice2_V_4_d0 = tmp_54_fu_1112_p4;

assign glPLSlice2_V_5_d0 = tmp_54_fu_1112_p4;

assign glPLSlice2_V_6_d0 = tmp_54_fu_1112_p4;

assign glPLSlice2_V_7_d0 = tmp_54_fu_1112_p4;

assign glPLSlice2_V_8_d0 = tmp_54_fu_1112_p4;

assign glPLSlice2_V_9_d0 = tmp_54_fu_1112_p4;

assign grp_fu_784_p4 = {{xNewIdx_V_fu_841_p2[9:4]}};

assign grp_fu_793_p2 = (tmp_12_reg_1558 | 9'd2);

assign grp_fu_798_p2 = (tmp_12_reg_1558 | 9'd3);

assign index_assign_1_1_cas_fu_1412_p1 = $signed(grp_fu_793_p2);

assign index_assign_1_2_cas_fu_1424_p1 = $signed(grp_fu_798_p2);

assign index_assign_1_s_fu_1398_p2 = (tmp_33_cast_fu_1387_p1 | 32'd1);

assign index_assign_5_1_cas_fu_1204_p1 = $signed(grp_fu_793_p2);

assign index_assign_5_2_cas_fu_1216_p1 = $signed(grp_fu_798_p2);

assign index_assign_5_s_fu_1190_p2 = (tmp_40_cast_fu_1179_p1 | 32'd1);

assign index_assign_9_1_cas_fu_996_p1 = $signed(grp_fu_793_p2);

assign index_assign_9_2_cas_fu_1008_p1 = $signed(grp_fu_798_p2);

assign index_assign_9_s_fu_982_p2 = (tmp_47_cast_fu_971_p1 | 32'd1);

assign newIndex3_fu_910_p1 = grp_fu_784_p4;

assign newIndex5_fu_890_p1 = grp_fu_784_p4;

assign newIndex6_fu_870_p1 = grp_fu_784_p4;

assign p_Repl2_2_1_fu_1480_p1 = tmp_22_fu_1472_p3;

assign p_Repl2_2_2_fu_1502_p1 = tmp_24_fu_1494_p3;

assign p_Repl2_2_3_fu_1524_p1 = tmp_27_fu_1516_p3;

assign p_Repl2_2_fu_1458_p1 = tmp_19_fu_1454_p1;

assign p_Repl2_4_1_fu_1272_p1 = tmp_36_fu_1264_p3;

assign p_Repl2_4_2_fu_1294_p1 = tmp_38_fu_1286_p3;

assign p_Repl2_4_3_fu_1316_p1 = tmp_40_fu_1308_p3;

assign p_Repl2_4_fu_1250_p1 = tmp_34_fu_1246_p1;

assign p_Repl2_5_1_fu_1064_p1 = tmp_49_fu_1056_p3;

assign p_Repl2_5_2_fu_1086_p1 = tmp_51_fu_1078_p3;

assign p_Repl2_5_3_fu_1108_p1 = tmp_53_fu_1100_p3;

assign p_Repl2_5_fu_1042_p1 = tmp_47_fu_1038_p1;

assign p_Result_12_3_fu_1436_p5 = {{{{tmp_18_fu_1428_p3}, {tmp_17_fu_1416_p3}}, {tmp_16_fu_1404_p3}}, {tmp_15_fu_1390_p3}};

assign p_Result_14_3_fu_1228_p5 = {{{{tmp_33_fu_1220_p3}, {tmp_32_fu_1208_p3}}, {tmp_31_fu_1196_p3}}, {tmp_30_fu_1182_p3}};

assign p_Result_16_3_fu_1020_p5 = {{{{tmp_46_fu_1012_p3}, {tmp_45_fu_1000_p3}}, {tmp_44_fu_988_p3}}, {tmp_43_fu_974_p3}};

assign p_s_fu_835_p2 = (tmp_fu_807_p2 + y_cast_fu_803_p1);

assign pol_read_read_fu_190_p2 = pol;

assign tmpData_V_1_fu_1141_p17 = xNewIdx_V_reg_1567[3:0];

assign tmpData_V_2_fu_933_p17 = xNewIdx_V_reg_1567[3:0];

assign tmpData_V_fu_1349_p17 = xNewIdx_V_reg_1567[3:0];

assign tmpTmpData_V_1_fu_1240_p2 = (4'd1 + p_Result_14_3_fu_1228_p5);

assign tmpTmpData_V_2_fu_1032_p2 = (4'd1 + p_Result_16_3_fu_1020_p5);

assign tmpTmpData_V_fu_1448_p2 = (4'd1 + p_Result_12_3_fu_1436_p5);

assign tmp_12_fu_823_p3 = {{tmp_s_fu_813_p4}, {2'd0}};

assign tmp_13_fu_852_p2 = ((glPLActiveSliceIdx_V == 2'd0) ? 1'b1 : 1'b0);

assign tmp_14_fu_1346_p1 = xNewIdx_V_reg_1567[3:0];

assign tmp_15_fu_1390_p3 = tmpData_V_fu_1349_p18[tmp_33_cast_fu_1387_p1];

assign tmp_16_fu_1404_p3 = tmpData_V_fu_1349_p18[index_assign_1_s_fu_1398_p2];

assign tmp_17_fu_1416_p3 = tmpData_V_fu_1349_p18[index_assign_1_1_cas_fu_1412_p1];

assign tmp_18_fu_1428_p3 = tmpData_V_fu_1349_p18[index_assign_1_2_cas_fu_1424_p1];

assign tmp_19_fu_1454_p1 = tmpTmpData_V_fu_1448_p2[0:0];

always @ (*) begin
    tmp_20_fu_1462_p4 = tmpData_V_fu_1349_p18;
    tmp_20_fu_1462_p4[tmp_33_cast_fu_1387_p1] = |(p_Repl2_2_fu_1458_p1);
end

assign tmp_21_fu_858_p2 = ((glPLActiveSliceIdx_V == 2'd1) ? 1'b1 : 1'b0);

assign tmp_22_fu_1472_p3 = tmpTmpData_V_fu_1448_p2[32'd1];

always @ (*) begin
    tmp_23_fu_1484_p4 = tmp_20_fu_1462_p4;
    tmp_23_fu_1484_p4[index_assign_1_s_fu_1398_p2] = |(p_Repl2_2_1_fu_1480_p1);
end

assign tmp_24_fu_1494_p3 = tmpTmpData_V_fu_1448_p2[32'd2];

always @ (*) begin
    tmp_25_fu_1506_p4 = tmp_23_fu_1484_p4;
    tmp_25_fu_1506_p4[index_assign_1_1_cas_fu_1412_p1] = |(p_Repl2_2_2_fu_1502_p1);
end

assign tmp_26_fu_864_p2 = ((glPLActiveSliceIdx_V == 2'd2) ? 1'b1 : 1'b0);

assign tmp_27_fu_1516_p3 = tmpTmpData_V_fu_1448_p2[32'd3];

always @ (*) begin
    tmp_28_fu_1528_p4 = tmp_25_fu_1506_p4;
    tmp_28_fu_1528_p4[index_assign_1_2_cas_fu_1424_p1] = |(p_Repl2_2_3_fu_1524_p1);
end

assign tmp_29_fu_1138_p1 = xNewIdx_V_reg_1567[3:0];

assign tmp_30_cast_fu_831_p1 = tmp_12_fu_823_p3;

assign tmp_30_fu_1182_p3 = tmpData_V_1_fu_1141_p18[tmp_40_cast_fu_1179_p1];

assign tmp_31_fu_1196_p3 = tmpData_V_1_fu_1141_p18[index_assign_5_s_fu_1190_p2];

assign tmp_32_fu_1208_p3 = tmpData_V_1_fu_1141_p18[index_assign_5_1_cas_fu_1204_p1];

assign tmp_33_cast_fu_1387_p1 = tmp_12_reg_1558;

assign tmp_33_fu_1220_p3 = tmpData_V_1_fu_1141_p18[index_assign_5_2_cas_fu_1216_p1];

assign tmp_34_fu_1246_p1 = tmpTmpData_V_1_fu_1240_p2[0:0];

always @ (*) begin
    tmp_35_fu_1254_p4 = tmpData_V_1_fu_1141_p18;
    tmp_35_fu_1254_p4[tmp_40_cast_fu_1179_p1] = |(p_Repl2_4_fu_1250_p1);
end

assign tmp_36_fu_1264_p3 = tmpTmpData_V_1_fu_1240_p2[32'd1];

always @ (*) begin
    tmp_37_fu_1276_p4 = tmp_35_fu_1254_p4;
    tmp_37_fu_1276_p4[index_assign_5_s_fu_1190_p2] = |(p_Repl2_4_1_fu_1272_p1);
end

assign tmp_38_fu_1286_p3 = tmpTmpData_V_1_fu_1240_p2[32'd2];

always @ (*) begin
    tmp_39_fu_1298_p4 = tmp_37_fu_1276_p4;
    tmp_39_fu_1298_p4[index_assign_5_1_cas_fu_1204_p1] = |(p_Repl2_4_2_fu_1294_p1);
end

assign tmp_40_cast_fu_1179_p1 = tmp_12_reg_1558;

assign tmp_40_fu_1308_p3 = tmpTmpData_V_1_fu_1240_p2[32'd3];

always @ (*) begin
    tmp_41_fu_1320_p4 = tmp_39_fu_1298_p4;
    tmp_41_fu_1320_p4[index_assign_5_2_cas_fu_1216_p1] = |(p_Repl2_4_3_fu_1316_p1);
end

assign tmp_42_fu_930_p1 = xNewIdx_V_reg_1567[3:0];

assign tmp_43_fu_974_p3 = tmpData_V_2_fu_933_p18[tmp_47_cast_fu_971_p1];

assign tmp_44_fu_988_p3 = tmpData_V_2_fu_933_p18[index_assign_9_s_fu_982_p2];

assign tmp_45_fu_1000_p3 = tmpData_V_2_fu_933_p18[index_assign_9_1_cas_fu_996_p1];

assign tmp_46_fu_1012_p3 = tmpData_V_2_fu_933_p18[index_assign_9_2_cas_fu_1008_p1];

assign tmp_47_cast_fu_971_p1 = tmp_12_reg_1558;

assign tmp_47_fu_1038_p1 = tmpTmpData_V_2_fu_1032_p2[0:0];

always @ (*) begin
    tmp_48_fu_1046_p4 = tmpData_V_2_fu_933_p18;
    tmp_48_fu_1046_p4[tmp_47_cast_fu_971_p1] = |(p_Repl2_5_fu_1042_p1);
end

assign tmp_49_fu_1056_p3 = tmpTmpData_V_2_fu_1032_p2[32'd1];

always @ (*) begin
    tmp_50_fu_1068_p4 = tmp_48_fu_1046_p4;
    tmp_50_fu_1068_p4[index_assign_9_s_fu_982_p2] = |(p_Repl2_5_1_fu_1064_p1);
end

assign tmp_51_fu_1078_p3 = tmpTmpData_V_2_fu_1032_p2[32'd2];

always @ (*) begin
    tmp_52_fu_1090_p4 = tmp_50_fu_1068_p4;
    tmp_52_fu_1090_p4[index_assign_9_1_cas_fu_996_p1] = |(p_Repl2_5_2_fu_1086_p1);
end

assign tmp_53_fu_1100_p3 = tmpTmpData_V_2_fu_1032_p2[32'd3];

always @ (*) begin
    tmp_54_fu_1112_p4 = tmp_52_fu_1090_p4;
    tmp_54_fu_1112_p4[index_assign_9_2_cas_fu_1008_p1] = |(p_Repl2_5_3_fu_1108_p1);
end

assign tmp_fu_807_p2 = x << 10'd2;

assign tmp_s_fu_813_p4 = {{y[8:2]}};

assign xNewIdx_V_fu_841_p2 = ($signed(p_s_fu_835_p2) - $signed(tmp_30_cast_fu_831_p1));

assign y_cast_fu_803_p1 = y;

always @ (posedge ap_clk) begin
    tmp_12_reg_1558[1:0] <= 2'b00;
end

endmodule //accumulateHW
