lappend pragmaStatus0 {pragma "ARRAY_PARTITION" source "E:/xfOpenCV/hls_2018_1/abmofParseEvents_SmallBitWidth/src/abmof_hw_accel.cpp" location "parseEvents" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "glPLSlice0"}
lappend pragmaStatus1 {pragma "ARRAY_PARTITION" source "E:/xfOpenCV/hls_2018_1/abmofParseEvents_SmallBitWidth/src/abmof_hw_accel.cpp" location "parseEvents" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "glPLSlice1"}
lappend pragmaStatus2 {pragma "ARRAY_PARTITION" source "E:/xfOpenCV/hls_2018_1/abmofParseEvents_SmallBitWidth/src/abmof_hw_accel.cpp" location "parseEvents" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "glPLSlice2"}
lappend pragmaStatus3 {pragma "INTERFACE" source "E:/xfOpenCV/hls_2018_1/abmofParseEvents_SmallBitWidth/src/abmof_hw_accel.cpp" location "parseEvents" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus4 {pragma "INTERFACE" source "E:/xfOpenCV/hls_2018_1/abmofParseEvents_SmallBitWidth/src/abmof_hw_accel.cpp" location "parseEvents" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus5 {pragma "RESOURCE" source "E:/xfOpenCV/hls_2018_1/abmofParseEvents_SmallBitWidth/src/abmof_hw_accel.cpp" location "parseEvents" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "glPLSlice0"}
lappend pragmaStatus6 {pragma "RESOURCE" source "E:/xfOpenCV/hls_2018_1/abmofParseEvents_SmallBitWidth/src/abmof_hw_accel.cpp" location "parseEvents" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "glPLSlice1"}
lappend pragmaStatus7 {pragma "RESOURCE" source "E:/xfOpenCV/hls_2018_1/abmofParseEvents_SmallBitWidth/src/abmof_hw_accel.cpp" location "parseEvents" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "glPLSlice2"}
lappend pragmaStatus8 {pragma "PIPELINE" source "E:/xfOpenCV/hls_2018_1/abmofParseEvents_SmallBitWidth/src/abmof_hw_accel.cpp" location "parseEvents/loop_1" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
