lappend pragmaStatus0 {pragma "INTERFACE" source "E:/xfOpenCV/hls_2018_1/abmofParseEvents/src/abmof_hw_accel.cpp" location "parseEvents" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus1 {pragma "INTERFACE" source "E:/xfOpenCV/hls_2018_1/abmofParseEvents/src/abmof_hw_accel.cpp" location "parseEvents" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus2 {pragma "INLINE" source "E:/xfOpenCV/hls_2018_1/abmofParseEvents/src/abmof_hw_accel.cpp" location "accumulateHW" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus3 {pragma "PIPELINE" source "E:/xfOpenCV/hls_2018_1/abmofParseEvents/src/abmof_hw_accel.cpp" location "parseEvents/loop_1" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus4 {pragma "OCCURRENCE" source "E:/xfOpenCV/hls_2018_1/abmofParseEvents/src/abmof_hw_accel.cpp" location "parseEvents/Cond_Region" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus5 {pragma "RESOURCE" source "E:/xfOpenCV/hls_2018_1/abmofParseEvents/src/abmof_hw_accel.cpp" location "parseEvents" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "glPLSlice0"}
lappend pragmaStatus6 {pragma "RESOURCE" source "E:/xfOpenCV/hls_2018_1/abmofParseEvents/src/abmof_hw_accel.cpp" location "parseEvents" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "glPLSlice1"}
lappend pragmaStatus7 {pragma "RESOURCE" source "E:/xfOpenCV/hls_2018_1/abmofParseEvents/src/abmof_hw_accel.cpp" location "parseEvents" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "glPLSlice2"}
lappend pragmaStatus8 {pragma "ARRAY_PARTITION" source "E:/xfOpenCV/hls_2018_1/abmofParseEvents/src/abmof_hw_accel.cpp" location "parseEvents" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "glPLSlice0"}
lappend pragmaStatus9 {pragma "ARRAY_PARTITION" source "E:/xfOpenCV/hls_2018_1/abmofParseEvents/src/abmof_hw_accel.cpp" location "parseEvents" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "glPLSlice1"}
lappend pragmaStatus10 {pragma "ARRAY_PARTITION" source "E:/xfOpenCV/hls_2018_1/abmofParseEvents/src/abmof_hw_accel.cpp" location "parseEvents" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "glPLSlice2"}
lappend pragmaStatus11 {pragma "INLINE" source "E:/xfOpenCV/hls_2018_1/abmofParseEvents/src/abmof_hw_accel.cpp" location "calcOF" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
